-- Expansão de cobertura normativa: ITA 25/2022 e Portaria Normativa 1.369/MD/2004
-- Mantém a arquitetura sem OpenAI/embeddings externos.

with alvo as (
  select id,titulo from normas where titulo in (
    'ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',
    'Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004'
  )
), novos(titulo,pagina,dispositivo,conteudo,metadata) as (
  values
  ('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',1,'Art. 1º, §§ 1º a 5º — marcações mínimas e redirecionamento','As armas importadas devem observar as marcações mínimas previstas na Portaria nº 213-COLOG/2021, e as embalagens de munições importadas devem observar as identificações mínimas previstas na Portaria nº 214-COLOG/2021. Não se autoriza completar no Brasil marcações ou identificações quando faltarem os requisitos mínimos indicados; nessas hipóteses, os produtos devem ser redirecionados ao país de origem.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','marcacao_importacao')),
  ('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',1,'Art. 1º, §§ 6º a 8º — locais e executor da marcação','A marcação ou identificação pode ocorrer no depósito do importador, no local de guarda do acervo quando o importador for pessoa física ou em instalação de empresa registrada no Exército. Local distinto é admitido quando o executor estiver registrado no SisFPC ou for armeiro credenciado pela Polícia Federal; a execução deve ser feita por pessoa física ou jurídica especializada.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','marcacao_importacao')),
  ('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',2,'Art. 2º — procedimento prévio do importador','O importador deve solicitar previamente a autorização para marcação das armas e/ou identificação das embalagens de munição, registrar a informação no processo de importação, providenciar a conferência física pelo SFPC, obter a Guia de Tráfego para deslocamento do recinto alfandegado ao local de marcação e, depois da execução, solicitar nova vistoria. A comercialização ou o registro no acervo somente ocorre após a conferência e liberação pelo SFPC.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','importacao_procedimento','nota_atualizacao','A ITA cita procedimentos da Portaria nº 1.729/2019, revogada pela Portaria C Ex nº 2.566/2025; aplicar o fluxo atual compatível com a norma superveniente.')),
  ('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',3,'Art. 3º — autorização excepcional','Quando a autorização prévia para marcação ou identificação não tiver sido solicitada por motivo justificável, pode ser requerida autorização excepcional à DFPC. Concedida a autorização, o importador deve regularizar o processo de importação, obter a Guia de Tráfego, realizar a marcação ou identificação e submeter a carga à vistoria do SFPC antes de qualquer liberação para comércio ou registro.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','importacao_excepcional','nota_atualizacao','Procedimentos de comércio exterior devem ser lidos em conjunto com a Portaria C Ex nº 2.566/2025.')),
  ('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',4,'Arts. 4º a 7º — SFPC e DFPC','O SFPC realiza análise documental e conferência física da carga, condiciona a liberação ao cumprimento das marcações ou identificações autorizadas, expede a Guia de Tráfego específica e realiza nova conferência após a execução. A DFPC analisa os pedidos de autorização, verifica a conformidade com as Portarias nº 213 e 214/2021 e registra a decisão no processo de importação.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','fiscalizacao_importacao','nota_atualizacao','Referências operacionais antigas devem ser compatibilizadas com a Portaria C Ex nº 2.566/2025.')),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004',1,'Art. 1º, incisos I e II — dados do proprietário e validade','O CRAF emitido pelos Comandos da Marinha, do Exército e da Aeronáutica deve conter os dados de identificação do proprietário e a validade do documento.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','craf')),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004',1,'Art. 1º, inciso III — dados da arma','O CRAF deve conter os dados da arma registrada, incluindo número do registro, tipo, marca, calibre, número de série e número de registro no SIGMA.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','craf')),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004',1,'Art. 1º, inciso IV e parágrafo único — expedição e porte','O CRAF deve indicar a data de expedição. Nos casos permitidos pela legislação, o documento pode conter a observação de que o militar está autorizado a portar a arma registrada e a abrangência territorial dessa autorização.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','craf_porte')),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004',1,'Anexo — modelos de CRAF atualizados em 2024','Os modelos de Certificado de Registro de Arma de Fogo constantes do Anexo foram substituídos pela Portaria GM-MD nº 132/2024, em vigor desde 1º de fevereiro de 2024. A aplicação deve considerar os modelos atualizados, inclusive a distinção entre CRAF não válido como porte e CRAF com autorização para porte quando cabível.',jsonb_build_object('origem','fonte_projeto','tipo','sintese_fiel','tema','craf_modelo','alteradora','Portaria GM-MD nº 132/2024'))
)
insert into trechos(norma_id,pagina,dispositivo,conteudo,metadata)
select a.id,n.pagina,n.dispositivo,n.conteudo,n.metadata
from novos n join alvo a on a.titulo=n.titulo
where not exists (select 1 from trechos t where t.norma_id=a.id and t.dispositivo=n.dispositivo and t.conteudo=n.conteudo);

insert into sinonimos_busca(termo,expansao,ativo,observacao,atualizado_em)
values
 ('marcacao importada','marcação arma importada identificação embalagem munição importada DFPC SFPC',true,'Marcação de PCE importado',now()),
 ('marcacao de armas importadas','marcação arma importada identificação embalagem munição importada DFPC SFPC',true,'Marcação de armas importadas',now()),
 ('embalagem municao importada','identificação embalagem munição importada marcação DFPC SFPC',true,'Identificação de embalagens de munição importada',now()),
 ('modelo craf','certificado de registro de arma de fogo modelo CRAF porte SIGMA',true,'Modelo de CRAF',now())
on conflict (termo) do update set expansao=excluded.expansao,ativo=excluded.ativo,observacao=excluded.observacao,atualizado_em=excluded.atualizado_em;
