-- Estrutura incremental para controle de vigência e rastreabilidade normativa.
-- Execute no Supabase somente após revisar o schema atual da tabela public.normas.

alter table if exists public.normas
  add column if not exists status_detalhado text,
  add column if not exists norma_principal boolean not null default true,
  add column if not exists usar_como_fundamento boolean not null default true,
  add column if not exists vigencia_inicio date,
  add column if not exists vigencia_fim date,
  add column if not exists ultima_verificacao date,
  add column if not exists observacao_vigencia text,
  add column if not exists palavras_chave text[] not null default '{}';

create table if not exists public.relacoes_normativas (
  id bigint generated by default as identity primary key,
  norma_id text not null references public.normas(id) on delete cascade,
  tipo text not null check (tipo in ('altera','revoga','revogada_por','complementa','regulamenta','substitui','consolida')),
  norma_relacionada text not null,
  dispositivo text,
  observacao text,
  created_at timestamptz not null default now()
);

create index if not exists relacoes_normativas_norma_id_idx
  on public.relacoes_normativas(norma_id);

-- Estados aceitos pela camada de aplicação. Mantemos text para facilitar migração
-- do schema atual, mas restringimos os valores novos por validação de aplicação.
comment on column public.normas.status is
  'vigente | vigente_com_alteracoes | parcialmente_vigente | ato_alterador | revogada | superada_materialmente | vigencia_a_confirmar';

-- Norma revogada, superada, de mera alteração ou ainda não confirmada não deve
-- ser usada automaticamente como fundamento de resposta.
update public.normas
set usar_como_fundamento = false
where lower(status) in ('revogada','superada_materialmente','ato_alterador','vigencia_a_confirmar');
