-- Expansão da camada de dispositivos literais conferidos.
-- Portarias 164/2023, 166/2023 e 167/2024.

with alvo as (
  select id,titulo from normas where titulo in (
    'Portaria nº 164 COLOG/C Ex, de dezembro de 2023',
    'Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023',
    'Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024'
  )
), dados(titulo,referencia,artigo,texto_literal,pagina,status,observacao) as (
values
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 8º e parágrafo único','8º','Os subtenentes e sargentos de carreira, em serviço ativo ou na inatividade, terão a autorização para portar arma de fogo assegurada, na forma do art. 53 do Decreto nº 11.615/2023, observadas as restrições previstas no inciso III do art. 13 destas normas. Parágrafo único. Serão autorizados também a portar arma de fogo os sargentos oriundos das escolas de formação de sargentos, ainda não estabilizados.',9,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 9º, caput e §§ 1º a 3º','9º','A comprovação da autorização para portar arma de fogo dos militares citados nos arts. 7º e 8º se dá por meio da apresentação da identificação militar e do CRAF do armamento conduzido. § 1º No caso de oficiais temporários e sargentos não estabilizados, a autorização para portar arma de fogo está vinculada à validade da identidade militar. § 2º Os militares inativos, para conservarem a autorização de porte de arma de fogo, deverão submeter-se ao teste de avaliação psicológica, conforme o art. 30 do Decreto nº 9.847/2019, a cada dez anos, a contar da data de transferência para a reserva remunerada. § 3º Quando o militar a que se refere o § 2º for sargento, cabo ou soldado deverá ser apresentado também o parecer favorável da Região Militar de vinculação para manutenção do porte de arma.',9,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 10, caput e incisos I e II','10','Excepcionalmente, poderá ser concedida autorização para portar arma de fogo, desde que sejam caracterizados os fatos e as circunstâncias que a justifiquem, para: I - sargentos temporários; e II - cabos, taifeiros ou soldados em serviço ativo ou na inatividade.',9,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 11 e parágrafo único','11','A autorização para portar arma de fogo terá abrangência em todo o território nacional. Parágrafo único. Caso o militar transporte mais de uma arma de fogo simultaneamente, apenas uma arma de fogo de porte poderá estar municiada.',9,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 13, incisos I a V','13','Não será concedida autorização para portar arma de fogo aos militares: I - alunos em cursos/estágios de formação; II - durante o Serviço Militar Inicial; III - praças com comportamento insuficiente ou mau; IV - inaptos em laudo de avaliação de aptidão psicológica para manuseio de arma de fogo; V - respondendo a inquérito policial, processo criminal ou condenado, com trânsito em julgado.',10,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 29 e §§ 1º e 2º','29','O transporte da arma de fogo pertencente a militar sem autorização para portá-la deverá ser feito com a respectiva Guia de Tráfego. § 1º A solicitação e a expedição da Guia de Tráfego dar-se-á conforme Instrução Técnico-Administrativa expedida pela Diretoria de Fiscalização de Produtos Controlados. § 2º A arma de fogo poderá ser transportada desmuniciada e acompanhada da munição, obedecido o limite anual de aquisição.',13,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 30, caput e §§ 1º e 2º','30','O proprietário de arma de fogo fica obrigado a comunicar imediatamente ao SIGMA o extravio, o furto, o roubo e a recuperação da arma. § 1º A comunicação do sinistro deverá ser feita na OM de vinculação, mediante apresentação do boletim de ocorrência. No caso de militar inativo, a comunicação poderá ser feita em qualquer OM do SisFPC. § 2º A OM deve publicar o sinistro em Boletim Interno e solicitar ao SFPC a atualização da situação da arma de fogo no SIGMA.',13,'vigente',null),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023','Normas, art. 31','31','O militar que possuir arma de fogo cadastrada no SIGMA, no caso de ser excluído das Forças Armadas, deverá providenciar imediatamente a transferência da arma para o SINARM, em face da nova situação, antes da data de vencimento do CRAF.',13,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 3º e parágrafo único','3º','A prática da atividade de colecionamento de armas de fogo será permitida aos maiores de vinte e cinco anos de idade e dependerá da concessão prévia de Certificado de Registro (CR), conforme o art. 41 do Decreto nº 11.615/2023. Parágrafo único. A atividade de colecionamento poderá ser exercida, ainda, por pessoa jurídica qualificada como museu e dependerá da expedição prévia de CR.',6,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 9º','9º','Atirador desportivo é a pessoa física registrada pelo SisFPC por meio do CR, filiada a entidade de tiro desportivo, que pratique habitualmente o tiro como modalidade de desporto de rendimento ou de desporto de formação, com emprego de arma de fogo ou de ar comprimido, conforme inciso XVII do art. 2º do Decreto nº 11.615/2023.',7,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 10, caput','10','A prática de tiro desportivo com emprego de arma de fogo, como modalidade de desporto de rendimento ou de desporto de formação, ocorrerá exclusivamente em entidades de tiro desportivo e será permitida aos maiores de dezoito anos de idade, por meio da concessão do CR, conforme o art. 34 do Decreto nº 11.615/2023.',7,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 18','18','O resultado do processo de concessão de registro será publicado em documento oficial permanente da OM do SisFPC.',10,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 22 e §§ 1º e 2º','22','A revalidação de registro é o processo de renovação de sua validade, mediante manifestação do colecionador, atirador desportivo ou caçador excepcional, via requerimento efetuado por meio do SisGCorp. § 1º A revalidação do registro deverá ser requerida antes da data de término da sua validade. § 2º A documentação para revalidação do registro é a prevista no § 2º do art. 17 destas normas.',11,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 38','38','A Guia de Tráfego Especial (GTE) é o documento comprobatório do porte de trânsito, a que se refere o art. 81 do Decreto nº 10.030/2019 e o art. 33 do Decreto nº 11.615/2023, para colecionador, atirador desportivo e caçador excepcional.',15,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 39','39','A solicitação e a expedição de GTE devem ser realizadas por intermédio do SisGCorp.',15,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 40, caput e § 1º','40','A GTE emitida para a atividade de caça excepcional, treinamento e/ou competição de tiro desportivo autoriza o atirador desportivo ou caçador excepcional a circular com produtos controlados, no período de sua validade e no itinerário compreendido entre os pontos de origem e destino, conforme consta na guia. § 1º A GTE autoriza o trânsito das armas de fogo registradas nos respectivos acervos, desmuniciadas e acompanhadas da munição acondicionada em recipiente próprio.',15,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 2º — redação vigente dada pela Portaria 225/2024','2º','Os integrantes, da ativa e na inatividade, das Polícias Militares e dos Corpos de Bombeiros Militares, dos estados e do Distrito Federal, e do Gabinete de Segurança Institucional da Presidência da República poderão adquirir até 4 (quatro) armas de fogo, das quais 2 (duas) poderão ser de uso restrito, conforme previsto no art. 27 da Lei nº 10.826/2003 e no art. 16 do Decreto nº 11.615/2023.',3,'alterado','Redação vigente incluída pela Portaria nº 225-COLOG/C Ex, de 28 de maio de 2024.'),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 3º','3º','A transferência de armas de fogo por integrantes das PM e dos CBM dos estados e do Distrito Federal e do GSI/PR segue, no que couber, as prescrições destas normas para aquisição de arma de fogo, de uso permitido ou restrito.',5,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 4º','4º','A iniciativa para transferência da arma de fogo cabe ao adquirente.',5,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 5º','5º','A transferência de arma de fogo cadastrada no SIGMA para o próprio SIGMA seguirá o modelo previsto no anexo I.',6,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 6º, caput e inciso I','6º','A transferência de arma de fogo cadastrada no SINARM para o SIGMA seguirá os seguintes procedimentos: I - armas de uso permitido: a autorização para transferência é de competência de cada órgão, nos termos do art. 16 do Decreto nº 11.615/2023.',6,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 7º, caput e § 1º','7º','A solicitação de cadastro de arma de fogo no SIGMA deve ser feita pelo órgão de vinculação do adquirente à RM de vinculação, com o envio dos processos de transferência e da publicação em documento oficial permanente. § 1º O deferimento da solicitação de cadastro no SIGMA deve ser publicado em boletim da RM de vinculação do órgão do adquirente.',6,'vigente',null)
)
insert into dispositivos (norma_id,referencia,artigo,texto_literal,pagina,status,observacao_vigencia,fonte_tipo,conferido,metadata)
select a.id,d.referencia,d.artigo,d.texto_literal,d.pagina,d.status,d.observacao,'pdf_oficial',true,
       jsonb_build_object('origem','PDF fornecido pelo usuário','carga','expand_literal_core_164_166_167_20261007')
from dados d join alvo a on a.titulo=d.titulo
on conflict (norma_id,referencia) do update set
  texto_literal=excluded.texto_literal,
  pagina=excluded.pagina,
  status=excluded.status,
  observacao_vigencia=excluded.observacao_vigencia,
  conferido=true,
  updated_at=now();
