-- Expansão da camada de dispositivos literais conferidos.
-- Lote: Lei 10.834/2003; Portarias C Ex 1.513, 1.518 e 1.541;
-- Portarias 189-EME/2020 e 212-COLOG/2021; Portaria Normativa 1.369/MD/2004;
-- Portaria Conjunta C Ex/DG-PF 2/2023 (redação consolidada onde indicado).

with src(titulo, referencia, artigo, paragrafo, inciso, texto_literal, status, observacao_vigencia, pagina, metadata) as (
  values
  ('Lei nº 10.834, de 29 de dezembro de 2003','Art. 1º','Art. 1º',null,null,'A Taxa de Fiscalização dos Produtos Controlados pelo Exército - TFPC, instituída pelo Decreto-Lei nº 2.025, de 30 de maio de 1983, será devida nas hipóteses e nos valores constantes do Anexo desta Lei.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Lei nº 10.834, de 29 de dezembro de 2003','Art. 1º, parágrafo único','Art. 1º','Parágrafo único',null,'O fato gerador da TFPC é o exercício regular do poder de polícia.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Lei nº 10.834, de 29 de dezembro de 2003','Art. 2º, caput','Art. 2º',null,null,'Os sujeitos passivos da TFPC são as pessoas físicas e jurídicas que exerçam atividades envolvendo produtos controlados pelo Exército.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Lei nº 10.834, de 29 de dezembro de 2003','Art. 2º, § 1º','Art. 2º','§ 1º',null,'As atividades referidas no caput incluem a fabricação, a recuperação, a manutenção, a utilização industrial, o manuseio, o uso esportivo, o colecionamento, a exportação, a importação, o desembaraço alfandegário, o armazenamento, o comércio e o tráfego.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Lei nº 10.834, de 29 de dezembro de 2003','Art. 3º','Art. 3º',null,null,'O pagamento da TFPC constitui requisito prévio para o processamento da pretensão do contribuinte.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Lei nº 10.834, de 29 de dezembro de 2003','Art. 4º, caput','Art. 4º',null,null,'São isentos do pagamento da TFPC:','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria C Ex nº 1.513, de 6 de abril de 2021','Art. 1º','Art. 1º',null,null,'As presentes Normas destinam-se a todos os militares e servidores civis integrantes do Sistema de Fiscalização de Produtos Controlados (SisFPC).','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.513, de 6 de abril de 2021','Art. 2º, caput','Art. 2º',null,null,'As Normas de Conduta dos Integrantes do SisFPC visam:','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.513, de 6 de abril de 2021','Art. 7º','Art. 7º',null,null,'Conflito de interesse é a situação gerada pelo confronto entre interesses públicos e privados que possa comprometer o interesse coletivo ou influenciar, de maneira imprópria, o desempenho da função pública.','vigente',null,6,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.513, de 6 de abril de 2021','Art. 8º','Art. 8º',null,null,'Informação Privilegiada é aquela que diz respeito a assuntos sigilosos ou é relevante ao processo de decisão no âmbito do Poder Executivo Federal, que tenha repercussão econômica ou financeira e que não seja de amplo conhecimento público.','vigente',null,6,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.513, de 6 de abril de 2021','Art. 20, caput','Art. 20',null,null,'São normas de conduta na relação com os usuários do SisFPC:','vigente',null,10,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.513, de 6 de abril de 2021','Art. 35','Art. 35',null,null,'As informações pessoais e técnicas sobre pessoas que exerçam atividades com Regulamento de Produtos Controlados pelo Exército (PCE) serão consideradas de acesso restrito, conforme o art. 60 do Regulamento de Produtos Controlados pelo Exército (Decreto nº 10.030, de 30 de setembro de 2019).','vigente',null,14,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 1º','Art. 1º',null,null,'Ficam estabelecidos os procedimentos administrativos relativos à destinação de produtos controlados pelo Exército (PCE) apreendidos pela Secretaria Especial da Receita Federal do Brasil.','vigente',null,null,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 2º','Art. 2º',null,null,'A destinação dos PCE apreendidos pela Secretaria Especial da Receita Federal do Brasil deverá ser procedida, conforme o previsto no Decreto-Lei nº 1.455, de 1976, Decreto nº 6.759, de 2009 e Portaria MF nº 282, de 9 de junho de 2011, ressalvados os PCE dos tipos explosivos, armas de fogo ou suas partes e peças controladas e munições, cuja destinação está prevista na Lei 10.826, de 2003 e no Decreto 9.847, de 2019.','vigente',null,null,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 3º','Art. 3º',null,null,'Os PCE dos tipos químicos, pirotécnicos, proteção balística e armas de pressão apreendidos pela Receita Federal do Brasil devem ser destruídos ou inutilizados, conforme previsto na Portaria MF nº 282, de 9 de junho de 2011, e somente poderão ser encaminhadas ao Exército Brasileiro, após a decretação de seu perdimento pelo órgão competente, devendo todos os custos com armazenamento, transporte e destruição serem assumidos pelo antigo proprietário ou responsável pelo material.','vigente',null,null,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 4º','Art. 4º',null,null,'As armas de fogo apreendidas devem ser informadas ao Departamento de Polícia Federal para fins de cadastramento no Sistema Nacional de Armas (SINARM), conforme previsto no art. 3º, inciso II, do §3º, do Decreto 9.847, de 2019, e verificação de indícios de infração penal.','vigente',null,null,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 5º','Art. 5º',null,null,'As armas de fogo apreendidas, quando não mais interessarem à persecução penal serão encaminhadas ao Comando do Exército para destruição ou doação aos órgãos de segurança pública, ou às Forças Armadas, na forma prevista no art. 25 da Lei 10.826, de 2003 e art. 45 do Decreto 9.847, de 2019.','vigente',null,null,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria C Ex nº 1.541, de 21 de junho de 2021','Art. 1º','Art. 1º',null,null,'Para os fins desta Portaria, Planejamento Estratégico Institucional para aquisição de PCE de uso restrito é o processo administrativo que proporciona sustentação metodológica para se estabelecer a melhor direção a ser seguida pelo órgão solicitante, visando alcançar a excelência no desempenho de suas missões institucionais.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.541, de 21 de junho de 2021','Art. 2º','Art. 2º',null,null,'Ficam estabelecidas as condições para a tramitação e aprovação de planejamento estratégico para aquisição de PCE de uso restrito pelos órgãos, instituições e corporações elencados no art. 34, incisos de I a XIII do Decreto nº 9.847, de 25 de junho de 2019.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.541, de 21 de junho de 2021','Art. 3º, caput','Art. 3º',null,null,'Os órgãos e instituições vinculados à estrutura do governo federal remeterão a proposta de planejamento estratégico diretamente ao Estado-Maior do Exército (EME), o qual, após análise do Chefe do EME, encaminhará o planejamento estratégico ao Gabinete do Comandante do Exército (Gab Cmt Ex) para que o Comandante do Exército (Cmt Ex) decida sobre a aprovação e, se for o caso, determine a publicação do planejamento estratégico em Boletim de Acesso Restrito do Exército (BARE).','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.541, de 21 de junho de 2021','Art. 4º, caput','Art. 4º',null,null,'As Polícias Militares (PM) e Corpos de Bombeiros Militares (CBM) remeterão a proposta de planejamento estratégico diretamente ao Comando Militar de Área (C Mil A) responsável pela área de atuação da instituição solicitante, ao qual caberá o protocolo inicial do processo e a verificação da instrução processual necessária à análise do planejamento estratégico.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria C Ex nº 1.541, de 21 de junho de 2021','Art. 4º, § 1º','Art. 4º','§ 1º',null,'Após a verificação da instrução processual da proposta, o C Mil A encaminhará ao Comando de Operações Terrestres (COTER), que, por sua vez, fará a apreciação e encaminhará ao EME.','vigente',null,1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria nº 189-EME, de 18 de agosto de 2020','Normas, art. 1º','Art. 1º',null,null,'Estas Normas estabelecem os procedimentos gerais de avaliação da conformidade de Produtos Controlados pelo Exército (PCE).','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria nº 189-EME, de 18 de agosto de 2020','Normas, art. 2º, caput','Art. 2º',null,null,'Constituem princípios gerais do processo de avaliação da conformidade de PCE:','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria nº 189-EME, de 18 de agosto de 2020','Normas, art. 2º, inciso I','Art. 2º',null,'I','assegurar que os produtos fabricados no País estejam em conformidade com as normas técnicas vigentes ou com as normas adotadas pelo Comando do Exército;','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria nº 189-EME, de 18 de agosto de 2020','Normas, art. 2º, inciso II','Art. 2º',null,'II','assegurar o atendimento aos requisitos de qualidade, de segurança, de durabilidade e de desempenho;','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria nº 212 COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 1º, inciso I','Art. 1º',null,'I','ACOMPANHAMENTO DE PRODUTO CONTROLADO PELO EXÉRCITO (PCE): ação de monitorar um produto ao longo do seu ciclo de vida.','vigente',null,3,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria nº 212 COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 5º, caput','Art. 5º',null,null,'O processo de cadastro de produtos no SisNaR compreende as seguintes fases:','vigente',null,5,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria nº 212 COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 5º, inciso I','Art. 5º',null,'I','criação dos Identificadores Individuais Seriados (IIS) para cada PCE, de acordo com o padrão estabelecido no Anexo destas normas, inicialmente, pelo fabricante ou pessoa jurídica importadora e posteriormente, com a evolução do SisNaR, pela DFPC;','vigente',null,5,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria nº 212 COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 6º','Art. 6º',null,null,'Cada PCE a ser rastreado deve ser identificado com o seu respectivo IIS, de acordo com o padrão previsto no Anexo.','vigente',null,5,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004','Art. 1º, caput','Art. 1º',null,null,'Autorizar os Comandos da Marinha, do Exército e da Aeronáutica a emitir Certificado de Registro de Arma de Fogo (CRAF), conforme os modelos constantes do anexo a esta Portaria, que serão impressos em papel-moeda fabricado pela Casa da Moeda do Brasil, e conterão os seguintes elementos:','alterado','Os modelos do Anexo foram substituídos pela Portaria GM-MD nº 132/2024; considerar o modelo atualmente vigente.',1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido","consolidacao":"anexo alterado pela Portaria GM-MD nº 132/2024"}'::jsonb),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004','Art. 1º, inciso I','Art. 1º',null,'I','dados do proprietário da arma: a) nome; b) número de inscrição no Cadastro de Pessoa Física; c) número da Carteira de Identidade; d) órgão expedidor;','alterado','Os modelos do Anexo foram substituídos pela Portaria GM-MD nº 132/2024; considerar o modelo atualmente vigente.',1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004','Art. 1º, inciso III','Art. 1º',null,'III','dados da arma registrada: a) número do registro; b) tipo; c) marca; d) calibre; e) número de série; f) número de registro no SIGMA;','alterado','Os modelos do Anexo foram substituídos pela Portaria GM-MD nº 132/2024; considerar o modelo atualmente vigente.',1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),
  ('Portaria Normativa nº 1.369/MD, de 25 de novembro de 2004','Art. 1º, parágrafo único','Art. 1º','Parágrafo único',null,'Nos casos permitidos pela legislação, constará do documento a observação de que o militar se encontra autorizado a portar a arma de fogo objeto do registro, nos termos do modelo “b” do anexo a esta Portaria, bem como a abrangência territorial da autorização para porte da arma de fogo registrada.','alterado','Os modelos do Anexo foram substituídos pela Portaria GM-MD nº 132/2024; considerar o modelo atualmente vigente.',1,'{"origem":"PDF fornecido pelo usuário","tipo":"texto_literal_conferido"}'::jsonb),

  ('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023','Art. 8º','Art. 8º',null,null,'As armas de fogo portáteis, longas, de alma raiada, semiautomáticas, de calibre nominal igual ou inferior ao ponto vinte e dois Long Rifle são de uso permitido.','alterado','Redação dada pela Portaria Conjunta C Ex/DG-PF nº 4, de 18 de julho de 2025.',8,'{"origem":"PDF consolidado fornecido pelo usuário","tipo":"texto_literal_conferido","redacao":"consolidada"}'::jsonb),
  ('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023','Art. 8º-A','Art. 8º-A',null,null,'As armas de fogo portáteis, longas, de alma raiada, semiautomáticas, de calibre nominal superior ao ponto vinte e dois Long Rifle são de uso restrito.','alterado','Dispositivo incluído pela Portaria Conjunta C Ex/DG-PF nº 4, de 18 de julho de 2025.',8,'{"origem":"PDF consolidado fornecido pelo usuário","tipo":"texto_literal_conferido","redacao":"consolidada"}'::jsonb),
  ('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023','Art. 9º','Art. 9º',null,null,'As armas do tipo multicalibre serão classificadas quanto ao uso considerando a munição de maior energia.','alterado','Interpretar em conjunto com o parágrafo único incluído pela Portaria Conjunta C Ex/DG-PF nº 4/2025 e com os anexos vigentes.',8,'{"origem":"PDF consolidado fornecido pelo usuário","tipo":"texto_literal_conferido","redacao":"consolidada"}'::jsonb),
  ('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023','Art. 9º, parágrafo único','Art. 9º','Parágrafo único',null,'No caso de armas multicalibre que compartilhem munições para armas de alma lisa e raiada, será considerada a classificação mais restritiva, de acordo com o previsto nos anexos desta Portaria.','alterado','Dispositivo incluído pela Portaria Conjunta C Ex/DG-PF nº 4, de 18 de julho de 2025.',8,'{"origem":"PDF consolidado fornecido pelo usuário","tipo":"texto_literal_conferido","redacao":"consolidada"}'::jsonb)
)
insert into public.dispositivos (norma_id, referencia, artigo, paragrafo, inciso, texto_literal, status, observacao_vigencia, pagina, fonte_tipo, conferido, metadata)
select n.id, s.referencia, s.artigo, s.paragrafo, s.inciso, s.texto_literal, s.status, s.observacao_vigencia, s.pagina, 'pdf_usuario', true, s.metadata
from src s
join public.normas n on n.titulo=s.titulo
where not exists (
  select 1 from public.dispositivos d
  where d.norma_id=n.id and d.referencia=s.referencia and d.texto_literal=s.texto_literal
);
