-- Expansão da cobertura literal dos Decretos 10.030/2019 e 11.615/2023.
-- Fonte: PDFs consolidados conferidos no projeto em 2026-10-07.

with novos(titulo,referencia,artigo,texto_literal,pagina,status,observacao) as (values
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 11, caput e incisos I a V','11','Fica instituído o Sistema de Fiscalização de Produtos Controlados - SisFPC, com a finalidade de promover a regulamentação, a autorização e a fiscalização de atividades referentes aos PCE, com vistas a atingir, de maneira eficiente, eficaz e efetiva, os seguintes objetivos: I - regulamentar, fiscalizar e autorizar as atividades de pessoas físicas e jurídicas referentes às atividades com PCE; II - definir o direcionamento estratégico do SisFPC; III - assegurar aos usuários do SisFPC a prestação de serviço eficiente; IV - assegurar a eficiência da gestão orçamentária, financeira e patrimonial; e V - valorizar e aperfeiçoar os seus recursos humanos.',7,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 12, incisos I a VI','12','A governança do SisFPC assegurará: I - a efetividade, a eficácia, a eficiência e a economicidade dos processos do SisFPC, garantida a entrega dos produtos e dos serviços; II - a transparência em suas ações, por meio do acesso da sociedade às informações geridas pelo SisFPC; III - a orientação para o usuário; IV - a auditoria de seus processos e a gestão de riscos; V - a responsabilidade na prestação de contas; e VI - o aperfeiçoamento técnico-profissional dos integrantes do SisFPC.',7,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 13, caput e incisos I a VI','13','Integram o SisFPC, na condição de auxiliares da fiscalização de PCE realizada pelo Comando do Exército: I - os órgãos de segurança pública; II - os órgãos da administração pública federal aos quais compete a supervisão de atividades relacionadas com o comércio exterior; III - a Secretaria Especial da Receita Federal do Brasil do Ministério da Economia; IV - o Instituto Nacional de Metrologia, Qualidade e Tecnologia - Inmetro; V - os serviços postal, similares ou de encomendas; e VI - as entidades de tiro desportivo.',7,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 14, caput','14','Os órgãos e as entidades da administração pública federal cooperarão com o Comando do Exército nas ações de fiscalização de PCE, quando solicitados.',8,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 23, caput e §§ 1º e 2º','23','Os produtos controlados de uso restrito e de uso permitido poderão ser comercializados em estabelecimentos comerciais. § 1º Os produtos do tipo explosivos não poderão ser objeto de exposição no local de venda. § 2º É vedada a comercialização de munição recarregada, exceto quanto à munição de salva e festim.',10,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 58, incisos I a IV','58','Os processos de controle de PCE são mecanismos operacionais, automatizados ou não, que têm a finalidade de: I - verificar a conformidade normativa do PCE em relação ao disposto neste Regulamento; II - produzir indicadores institucionais; III - fornecer informações para subsidiar a tomada de decisão; e IV - permitir a fiscalização efetiva de PCE pelo Comando do Exército.',16,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 74, caput e §§ 1º e 2º','74','A aquisição de PCE será autorizada pelo Comando do Exército. § 1º A aquisição de que trata o caput se refere a qualquer forma de aquisição que implique mudança de titularidade do PCE. § 2º A aquisição de PCE será documentada, com identificação do alienante, do adquirente e do produto.',17,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, arts. 80 a 82','80-82','Para fins do disposto neste Regulamento, tráfego é a circulação de PCE no território nacional. A guia de tráfego é o documento que materializa a autorização para o tráfego de PCE no território nacional e corresponde ao porte de trânsito previsto no art. 24 da Lei nº 10.826, de 2003. A pessoa que transportar PCE deverá portar a guia de tráfego correspondente aos produtos.',18,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 84, caput e § 1º','84','A autorização para o desembaraço alfandegário de PCE é o tratamento administrativo que antecede o deferimento da licença de importação ou a efetivação do registro de exportação, ou de documentos equivalentes, e compreende o exame documental e a conferência física. § 1º Para efeitos de desembaraço alfandegário, os PCE são classificados em três faixas.',19,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, arts. 98 e 99','98-99','Para fins do disposto neste Regulamento, a segurança refere-se à segurança de área e à segurança de PCE. A segurança de área corresponde à observação das condições de segurança das instalações onde haja atividade com PCE, contra acidentes que possam colocar em risco a integridade de pessoas e de bens. A segurança de PCE corresponde à adoção de medidas contra desvios, extravios, roubos e furtos de bens e aquisição ilícita do conhecimento relativo às atividades com PCE, a fim de evitar a sua utilização na prática de ilícitos. O planejamento e a implementação das medidas de segurança serão de responsabilidade da pessoa jurídica detentora de registro e serão consubstanciadas em um plano de segurança de PCE.',21,'vigente',null),
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, arts. 110 e 111','110-111','As infrações administrativas às normas de fiscalização de PCE e as sanções administrativas são aquelas previstas neste Regulamento. Para fins do disposto neste Regulamento, considera-se infração administrativa a ação ou a omissão de pessoas físicas ou jurídicas que violem norma jurídica referente a PCE. São infrações administrativas às normas de fiscalização, entre outras, fabricar, comercializar, importar, exportar, prestar serviço, utilizar, colecionar ou praticar tiro desportivo com PCE sem autorização ou em desacordo com a autorização concedida.',22,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 18, caput e §§ 1º e 2º','18','A aquisição de arma de fogo para a prática de caça excepcional, de tiro desportivo ou de colecionamento observará os requisitos estabelecidos neste Decreto e dependerá da apresentação de CR pelo interessado. § 1º O CRAF resultante da aquisição vinculará o uso da arma de fogo exclusivamente à prática da atividade à qual foi apostilada no CR. § 2º A aquisição de arma de fogo por museu dependerá da apresentação prévia de CR, nos termos do disposto no § 3º do art. 31.',17,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 30, caput','30','Os caçadores excepcionais, os atiradores desportivos e os colecionadores constituem grupos específicos, diferenciados em função da finalidade para a qual necessitam do acesso à arma de fogo, regulados nos termos deste Decreto e das normas complementares editadas pelo Comando do Exército.',21,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 31, caput e §§ 1º a 3º','31','A prática das atividades de caça excepcional, de tiro desportivo e de colecionamento de armas de fogo dependerá da concessão prévia de CR pelo Comando do Exército, vinculado à finalidade pretendida pelo interessado. § 1º O interessado que pretenda praticar mais de uma das atividades poderá requerer o correspondente apostilamento do CR, atendidos os requisitos específicos de cada modalidade. § 2º A arma de fogo adquirida somente poderá ser empregada nos termos do respectivo apostilamento autorizado. § 3º A atividade de colecionamento exercida por museu dependerá de prévia concessão de CR pelo Comando do Exército.',22,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 32, incisos I e II','32','Ficam vedadas: I - a concessão de CRAF e de CR a menor de vinte e cinco anos de idade para as atividades de colecionamento e de caça excepcional; e II - a prática de tiro desportivo para menores de quatorze anos de idade.',22,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 33, caput e §§ 1º a 3º','33','O porte de trânsito será concedido pelo Comando do Exército, mediante emissão da guia de tráfego, a caçadores excepcionais, atiradores desportivos, colecionadores e representantes estrangeiros em competição internacional oficial de tiro realizada no território nacional. § 1º O porte de trânsito autoriza o trânsito com armas de fogo registradas nos acervos, desmuniciadas, acompanhadas da munição acondicionada em recipiente próprio. § 2º Terá validade em trajeto preestabelecido, por período predeterminado e de acordo com a finalidade declarada no registro correspondente. § 3º A guia de tráfego será emitida por meio de plataforma de serviço digital do Comando do Exército.',22,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 34, caput e §§ 1º a 7º','34','A prática de tiro desportivo com emprego de arma de fogo ocorrerá exclusivamente em entidades de tiro desportivo e será permitida aos maiores de dezoito anos de idade, por meio da concessão do CR. Poderá ser concedido extraordinariamente CR aos maiores de quatorze e menores de dezoito anos nas condições previstas no § 1º. É permitida a prática de airsoft ou paintball aos maiores de quatorze anos, independentemente de CR. A autorização para recarga de munição poderá ser realizada por órgãos de segurança pública, para treinamento, e por entidades de tiro desportivo. É proibida a prática de tiro recreativo com armas de fogo por pessoas não registradas como atiradores.',23,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 39, caput, incisos I a III e parágrafo único','39','A caça excepcional possui finalidade exclusiva de controle de fauna invasora em locais onde o abate se mostre imprescindível para proteger lavouras, pomares e rebanhos da ação predatória ou destruidora de animais e somente será autorizada pelo Comando do Exército mediante a apresentação dos documentos e requisitos previstos no artigo. O limite é de até seis armas de fogo, das quais duas poderão ser de uso restrito, e até quinhentas munições por ano, por arma.',29,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 40, caput e §§ 1º e 2º','40','Aos maiores de vinte e cinco anos de idade, residentes em áreas rurais, que comprovem depender do emprego de arma de fogo para prover sua subsistência alimentar familiar será concedido pela Polícia Federal o porte, na categoria caçador para subsistência, de uma arma de uso permitido, de tiro simples, com um ou dois canos, de alma lisa e de calibre igual ou inferior a dezesseis, observados os requisitos do artigo.',30,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 41, caput e § 1º','41','A prática da atividade de colecionamento de armas de fogo será permitida aos maiores de vinte e cinco anos de idade e dependerá da concessão prévia de CR, nos termos do disposto em regulamentação do Comando do Exército. É vedado o colecionamento das categorias de armas previstas no § 1º, inclusive automáticas de qualquer calibre ou longas semiautomáticas de calibre de uso restrito cujo primeiro lote de fabricação tenha menos de setenta anos.',30,'vigente',null)
)
insert into dispositivos (norma_id,referencia,artigo,texto_literal,pagina,status,observacao_vigencia,fonte_tipo,conferido,metadata)
select n.id,v.referencia,v.artigo,v.texto_literal,v.pagina,v.status,v.observacao,'pdf_oficial',true,jsonb_build_object('origem','PDF consolidado fornecido no projeto','curadoria','2026-10-07')
from novos v join normas n on n.titulo=v.titulo
on conflict (norma_id,referencia) do nothing;
