-- Expande a camada de texto literal conferido para normas que ainda estavam sem dispositivos.
-- Aplicado previamente no projeto Supabase em 07/10/2026.
-- Fontes conferidas: ITA 25/2022, ITA 33/2026, Portaria 800/2020,
-- Portaria C Ex 1.757/2022, Portaria C Ex 2.566/2025 e Portaria 214/2021.

with alvo as (
  select id,titulo from normas where titulo in (
    'ITA nº 25 DFPC/COLOG, de 15 de junho de 2022',
    'ITA nº 33 DFPC/COLOG, de 22 de junho de 2026',
    'Portaria nº 800, de 14 de agosto de 2020',
    'Portaria C Ex nº 1.757, de 31 de maio de 2022',
    'Portaria C Ex nº 2.566, de 8 de outubro de 2025',
    'Portaria nº 214-COLOG/C Ex, de 15 de setembro de 2021'
  )
), dados(titulo,referencia,artigo,paragrafo,inciso,texto_literal,pagina,status,observacao_vigencia,metadata) as (values
('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022','Art. 1º','Art. 1º',null,null,'Estabelecer os procedimentos para as marcações de PCE importados de que trata o §1º do art. 10 das normas reguladoras dos dispositivos de segurança e dos procedimentos para identificação e marcação de armas de fogo e suas peças, fabricadas no país, exportadas e importadas, aprovadas pela Portaria nº 213-COLOG, de 15 de setembro de 2021; e o art. 2º das normas reguladoras dos procedimentos para identificação, marcação das munições e suas embalagens no âmbito do Sistema de Fiscalização de Produtos Controlados (SisFPC), aprovadas pela Portaria nº 214-COLOG, de 15 de setembro de 2021.',1,'vigente',null,'{"origem":"ITA 25/2022","tipo":"texto_literal"}'::jsonb),
('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022','Art. 1º, §§ 3º a 5º','Art. 1º','§§ 3º a 5º',null,'§3º Não serão autorizadas as marcações no Brasil das armas importadas que não possuírem as marcações mínimas previstas no §1º do art. 10 das normas reguladoras, aprovadas pela Portaria nº 213-COLOG, de 2021. §4º Não serão autorizadas as identificações no Brasil das embalagens das munições importadas que não possuírem as marcações mínimas previstas no art. 3º das normas reguladoras, aprovadas pela Portaria nº 214-COLOG, de 2021. §5º As armas importadas que não possuírem as marcações mínimas previstas no §1º do art. 10 das normas reguladoras, aprovadas pela Portaria nº 213-COLOG, de 2021; e as embalagens das munições importadas que não possuírem as marcações mínimas previstas no art. 3º das normas reguladoras, aprovadas pela Portaria nº 214-COLOG, de 2021, devem ser redirecionadas para o país de origem.',1,'vigente',null,'{"origem":"ITA 25/2022","tipo":"texto_literal"}'::jsonb),
('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022','Art. 1º, §§ 6º a 8º','Art. 1º','§§ 6º a 8º',null,'§6º As armas e as munições podem ser marcadas/identificadas: I - no depósito do importador (próprio ou terceirizado); II - no local de guarda do acervo quando o importador for pessoa física; ou III - em instalações de empresa registrada no Exército. §7º Admite-se a marcação/identificação em local distinto do previsto no caput, desde que o marcador/identificador seja registrado no SisFPC ou seja armeiro credenciado pela Polícia Federal. §8º As marcações/identificações devem ser realizadas por pessoa física ou jurídica especializada.',1,'vigente',null,'{"origem":"ITA 25/2022","tipo":"texto_literal"}'::jsonb),
('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022','Art. 2º','Art. 2º',null,null,'O importador, pessoa física ou jurídica, deverá solicitar, previamente ao registro da Licença de Importação (LI), as marcações das armas e/ou as identificações das embalagens de munição, conforme os seguintes procedimentos.',2,'vigencia_a_confirmar','O fluxo original cita a Portaria C Ex nº 1.729/2019, revogada pela Portaria C Ex nº 2.566/2025. A regra específica de marcação permanece útil, mas o procedimento de comércio exterior deve ser compatibilizado com a norma vigente.','{"origem":"ITA 25/2022","tipo":"texto_literal","alerta":"referencia_norma_revogada"}'::jsonb),
('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022','Art. 3º','Art. 3º',null,null,'Poderá ser autorizada em caráter excepcional a marcação de armas e/ou a identificação de munição importada, quando o importador não tenha solicitado autorização prévia por motivos justos.',2,'vigente',null,'{"origem":"ITA 25/2022","tipo":"texto_literal"}'::jsonb),
('ITA nº 25 DFPC/COLOG, de 15 de junho de 2022','Art. 4º','Art. 4º',null,null,'O SFPC responsável pela conferência física dos PCE importados, deverá realizar os seguintes procedimentos.',3,'vigencia_a_confirmar','O dispositivo remete à Portaria C Ex nº 1.729/2019, revogada pela Portaria C Ex nº 2.566/2025; usar somente após compatibilização do fluxo com a norma de comércio exterior vigente.','{"origem":"ITA 25/2022","tipo":"texto_literal","alerta":"referencia_norma_revogada"}'::jsonb),
('ITA nº 33 DFPC/COLOG, de 22 de junho de 2026','Art. 1º','Art. 1º',null,null,'Fica aprovado o Manual do Usuário do Sistema de Controle de Veículos Automotores Blindados e Proteções Balísticas (SICOVAB), anexo a esta Instrução Técnico-Administrativa.',2,'vigente',null,'{"origem":"ITA 33/2026","tipo":"texto_literal"}'::jsonb),
('ITA nº 33 DFPC/COLOG, de 22 de junho de 2026','Art. 2º','Art. 2º',null,null,'Fica estabelecido que as alterações do Manual do Usuário do SICOVAB sejam realizadas por demanda, observados os atos normativos de regência.',2,'vigente',null,'{"origem":"ITA 33/2026","tipo":"texto_literal"}'::jsonb),
('ITA nº 33 DFPC/COLOG, de 22 de junho de 2026','Art. 3º','Art. 3º',null,null,'Fica revogada a Instrução Técnico-Administrativa nº 29, de 31 de janeiro de 2025.',2,'vigente',null,'{"origem":"ITA 33/2026","tipo":"texto_literal"}'::jsonb),
('ITA nº 33 DFPC/COLOG, de 22 de junho de 2026','Anexo A, I.2 — Escopo do SICOVAB',null,null,null,'O SICOVAB é a ferramenta de gestão utilizada para o gerenciamento das atividades que envolvem os seguintes Produtos Controlados pelo Exército (PCE) do tipo “proteção balística”: a. veículos automotores blindados (VAB) especializados e não especializados, inclusive os veículos especiais de transporte de valores (VETV), ou “carro-forte”; b. blindagens balísticas opacas e transparentes; e c. coletes balísticos, exclusivamente no fluxo de aquisição por pessoa física no comércio especializado, desde a análise e emissão da autorização de aquisição pela Região Militar de vinculação até a validação da venda pelo fornecedor, sem prejuízo da carga prévia de documentos fiscais pelo fabricante ou importador quando necessária à rastreabilidade do processo.',4,'vigente',null,'{"origem":"ITA 33/2026","tipo":"texto_literal","secao":"manual_sicovab"}'::jsonb),
('ITA nº 33 DFPC/COLOG, de 22 de junho de 2026','Anexo A, III.6.a — Autorização prévia para blindagem',null,null,null,'A solicitação de Autorização Prévia para blindagem de veículo inicia com o lançamento do número e da data de autenticação do pagamento da taxa, exceto para veículo destinado à comercialização ou à exportação.',10,'vigente',null,'{"origem":"ITA 33/2026","tipo":"texto_literal","secao":"manual_sicovab"}'::jsonb),
('Portaria nº 800, de 14 de agosto de 2020','Art. 1º','Art. 1º',null,null,'Fica aprovada a tabela de classificação do nível de risco de atividades econômicas sujeitas a ato de liberação por órgãos do Sistema de Fiscalização de Produtos Controlados pelo Exército (SisFPC), conforme o anexo único, desta portaria.',1,'vigente',null,'{"origem":"Portaria 800/2020","tipo":"texto_literal"}'::jsonb),
('Portaria nº 800, de 14 de agosto de 2020','Art. 2º','Art. 2º',null,null,'Fica estabelecido que as atividades econômicas relacionadas a produtos controlados pelo Exército (PCE) não sejam classificadas no nível de risco I.',1,'vigente',null,'{"origem":"Portaria 800/2020","tipo":"texto_literal"}'::jsonb),
('Portaria nº 800, de 14 de agosto de 2020','Art. 2º, parágrafo único','Art. 2º','parágrafo único',null,'A ausência de classificação no nível de risco I a que se refere o caput, leva em consideração a extensão, a gravidade e o grau de irreparabilidade do impacto causado à sociedade, na hipótese de ocorrência de evento danoso envolvendo algum PCE.',1,'vigente',null,'{"origem":"Portaria 800/2020","tipo":"texto_literal"}'::jsonb),
('Portaria nº 800, de 14 de agosto de 2020','Art. 3º','Art. 3º',null,null,'Fica determinado que a tabela de classificação de risco de que trata o art. 1º seja revista periodicamente para fins de inclusão, exclusão e reclassificação das atividades econômicas sujeitas a ato de liberação por órgãos do SisFPC.',1,'vigente',null,'{"origem":"Portaria 800/2020","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 1.757, de 31 de maio de 2022','Art. 54','Art. 54',null,null,'Cabe ao COLOG, por intermédio da DFPC, supervisionar o SisFPC, a fim de permitir ao Comando do Exército o cumprimento da missão de regulamentação, autorização e fiscalização do exercício, por pessoas físicas ou jurídicas, das atividades relacionadas com PCE de fabricação, comércio, importação, exportação, utilização, prestação de serviços, colecionamento, tiro desportivo ou caça.',11,'vigente',null,'{"origem":"Portaria C Ex 1.757/2022","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 1.757, de 31 de maio de 2022','Art. 55, inciso VIII','Art. 55',null,'VIII','receber, por intermédio da DFPC, as solicitações de aquisição e/ou importação de armas de fogo, munições e demais produtos controlados, todos de uso restrito, exceto as oriundas das instituições elencadas no art. 34, incisos IX e X, do Decreto nº 9.847, de 25 de junho de 2019, e verificar o alinhamento entre as solicitações e o planejamento estratégico aprovado para emissão de autorização;',12,'vigente','Aplicar em conjunto com a regulamentação superveniente pertinente às instituições alcançadas.','{"origem":"Portaria C Ex 1.757/2022","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 1.757, de 31 de maio de 2022','Art. 55, inciso IX','Art. 55',null,'IX','emitir autorização ao órgão requerente, informando ao fornecedor do PCE de uso restrito, por intermédio da DFPC, no caso de aquisição no mercado nacional, e anuir a Licença de Importação, no caso de aquisição por importação;',12,'vigente',null,'{"origem":"Portaria C Ex 1.757/2022","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 1.757, de 31 de maio de 2022','Art. 56, incisos I a V','Art. 56',null,'I a V','São atribuições da DFPC: I - autorizar as importações de produtos controlados; II - autorizar as aquisições de PCE para os órgãos e as entidades da administração pública, no caso das Forças Auxiliares, em coordenação com o COTER; III - designar Organismo de Avaliação de Conformidade (OAC) para avaliação de produtos controlados, de acordo com norma específica; IV - efetuar o registro das empresas fabricantes de produtos controlados e promover as medidas necessárias para que o registro das demais empresas que atuem em outras atividades com tais produtos, em todo o território nacional, realize-se de acordo com as normas em vigor; V - autorizar atividades relativas a PCE, de acordo com as normas em vigor;',12,'vigente',null,'{"origem":"Portaria C Ex 1.757/2022","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 2.566, de 8 de outubro de 2025','Normas, art. 1º','Art. 1º',null,null,'Os procedimentos para o licenciamento e a inspeção da mercadoria em recinto alfandegado nas operações de importação de Produtos Controlados pelo Exército (PCE) seguirão o disposto nestas Normas, ressalvadas as importações realizadas diretamente pelas Forças Armadas.',1,'vigente',null,'{"origem":"Portaria C Ex 2.566/2025","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 2.566, de 8 de outubro de 2025','Normas, art. 2º, §§ 1º a 3º','Art. 2º','§§ 1º a 3º',null,'O controle administrativo sobre PCE será efetuado por meio de tratamentos administrativos sobre operações de importação de mercadoria. § 1º Os tratamentos administrativos a que se refere o caput serão aplicados por meio do Portal Único de Comércio Exterior e compreendem: I - Licenças, Permissões, Certificados e Outros Documentos (LPCO), para múltiplas operações de importação e exportação; e II - conferência na Declaração Única de Importação (DUIMP) pelo Exército. § 2º As LPCO para importação de PCE serão emitidas de modo a amparar operações relativas a mais de uma declaração de importação, observado o limite do prazo previsto no art. 9º destas Normas e da quantidade nelas estabelecidas. § 3º A conferência do Exército abrange a apreciação da documentação e a inspeção da mercadoria, de forma física ou remota.',1,'vigente',null,'{"origem":"Portaria C Ex 2.566/2025","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 2.566, de 8 de outubro de 2025','Normas, art. 55 e § 1º','Art. 55','§ 1º',null,'A admissão temporária de armas, munições e acessórios de atirador desportivo estrangeiro dar-se-á mediante registro de LPCO pela entidade de tiro ou órgão responsável pelo evento, com antecedência mínima de trinta dias corridos, considerando a data de chegada no País. § 1º Deverão constar do processo para admissão temporária: I - cópia do passaporte do atirador estrangeiro; II - respectiva taxa de fiscalização de produtos controlados e seu comprovante, conforme a Lei nº 10.834/2003; III - declaração de ciência e compromisso do atleta estrangeiro, contendo anuência das seguintes exigências: a) transitar apenas pelo itinerário previsto na Guia de Tráfego; b) não manter a arma em condições de pronto emprego fora do local de competição; e c) reexportar os PCE ao término do evento que motivou a admissão temporária.',8,'vigente',null,'{"origem":"Portaria C Ex 2.566/2025","tipo":"texto_literal"}'::jsonb),
('Portaria C Ex nº 2.566, de 8 de outubro de 2025','Normas, art. 64','Art. 64',null,null,'Para o registro da DUIMP deverá ser anexada a seguinte documentação no Portal Único de Comércio Exterior: I - invoice; II - packing list; III - conhecimento de embarque; IV - respectiva taxa de fiscalização de produtos controlados e seu comprovante, conforme a Lei nº 10.834/2003; e V - planilha SICOFA, quando for o caso.',9,'vigente',null,'{"origem":"Portaria C Ex 2.566/2025","tipo":"texto_literal"}'::jsonb),
('Portaria nº 214-COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 2º','Art. 2º',null,null,'Todas as munições e seus insumos, comercializadas no Brasil, oriundas de fabricantes nacionais ou importadas, deverão estar acondicionadas até seu consumo, em embalagens gravadas com sistema de código unidimensional ou bidimensional, que permita a identificação do fabricante, comerciante (lojista ou importador), lote, código de rastreabilidade, calibre e quantidade.',3,'vigente',null,'{"origem":"Portaria 214/2021","tipo":"texto_literal"}'::jsonb),
('Portaria nº 214-COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 3º','Art. 3º',null,null,'As munições fabricadas no país ou importadas deverão apresentar, no mínimo, as seguintes marcações na base do estojo: I – nome ou marca do fabricante; e II – calibre nominal.',3,'vigente',null,'{"origem":"Portaria 214/2021","tipo":"texto_literal"}'::jsonb),
('Portaria nº 214-COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 4º','Art. 4º',null,null,'Toda munição e seus insumos, destinadas para os órgãos, instituições e entidades discriminadas neste artigo, deverá conter código de rastreabilidade de munição gravado na base dos estojos, o qual permita identificar o fabricante, o lote e o órgão adquirente, em cumprimento ao que determina o § 2º do art. 23 da Lei nº 10.826, de 22 de dezembro de 2003.',4,'vigente',null,'{"origem":"Portaria 214/2021","tipo":"texto_literal"}'::jsonb),
('Portaria nº 214-COLOG/C Ex, de 15 de setembro de 2021','Normas, art. 5º','Art. 5º',null,null,'O lote rastreável de munição não poderá exceder a 10.000 (dez mil) unidades, marcado com o mesmo código de rastreabilidade de munição.',5,'vigente',null,'{"origem":"Portaria 214/2021","tipo":"texto_literal"}'::jsonb)
)
insert into dispositivos (norma_id,referencia,artigo,paragrafo,inciso,texto_literal,pagina,status,observacao_vigencia,fonte_tipo,conferido,metadata)
select a.id,d.referencia,d.artigo,d.paragrafo,d.inciso,d.texto_literal,d.pagina,d.status,d.observacao_vigencia,'pdf_conferido',true,d.metadata
from dados d join alvo a on a.titulo=d.titulo
on conflict (norma_id,referencia) do update set
 texto_literal=excluded.texto_literal,
 pagina=excluded.pagina,
 status=excluded.status,
 observacao_vigencia=excluded.observacao_vigencia,
 fonte_tipo=excluded.fonte_tipo,
 conferido=excluded.conferido,
 metadata=excluded.metadata,
 updated_at=now();
