-- Expande a camada de dispositivos literais conferidos em normas operacionais.
-- Aplicada em produção em 2026-10-07.

with src(norm_like, referencia, artigo, paragrafo, inciso, alinea, item, texto_literal, pagina, status, alteradora_like, observacao) as (
  values
  ('%Lei nº 10.834%','Art. 4º, inciso I','4º',null,'I',null,null,$$a União, os Estados, o Distrito Federal, os Municípios e as respectivas autarquias e fundações públicas;$$,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 4º, inciso II','4º',null,'II',null,null,$$as instituições de ensino e as instituições de pesquisa técnica ou científica, oficialmente reconhecidas;$$,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 4º, inciso III','4º',null,'III',null,null,$$as pessoas físicas ou jurídicas que usarem produtos controlados apenas como fertilizante;$$,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 4º, inciso IV','4º',null,'IV',null,null,$$os hospitais, as clínicas médicas e congêneres quando usarem produtos controlados apenas para fins medicinais;$$,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 4º, inciso V','4º',null,'V',null,null,$$as pessoas físicas ou jurídicas que usarem produtos controlados apenas na purificação de água, tanto para abastecimento quanto para outros fins de comprovada utilidade pública;$$,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 4º, inciso VI','4º',null,'VI',null,null,$$as farmácias e drogarias que aviem receitas ou vendam produtos farmacêuticos, todos dentro do limite de duzentos e cinqüenta mililitros;$$,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 4º, inciso VII','4º',null,'VII',null,null,$$o comércio de brinquedos que, no ramo dos produtos controlados, apenas transacione com armas de pressão por ação de mola, de uso permitido.$$ ,1,'vigente',null,null),
  ('%Lei nº 10.834%','Art. 5º','5º',null,null,null,null,$$Os recursos provenientes da arrecadação da TFPC serão creditados diretamente ao Fundo do Exército, na forma definida pelo Poder Executivo, e destinados ao custeio e ao investimento nas atividades de fiscalização de produtos controlados pelo Exército.$$ ,1,'vigente',null,null),

  ('%08-D Log%','Normas, art. 3º','3º',null,null,null,null,$$Todos os fogos de artifício, artifícios pirotécnicos e artefatos similares, destinados a espetáculos, festejos e folguedos, fabricados no País ou importados, devem ser submetidos à avaliação técnica para verificação de sua conformidade, à luz da legislação de referência.$$ ,3,'vigente',null,null),
  ('%08-D Log%','Normas, art. 4º, caput — redação 2019','4º','caput',null,null,null,$$A avaliação da conformidade dos produtos de que tratam estas Normas deve ser efetuada por Organismo de Avaliação da Conformidade (OAC) nos termos do Decreto Nº 10.030, de 30 de setembro de 2019.$$ ,4,'alterado','%148-COLOG%','Redação dada pela Portaria nº 148-COLOG/2019.'),
  ('%08-D Log%','Normas, art. 4º, § 1º — redação 2019','4º','§ 1º',null,null,null,$$Todos os custos relativos à certificação de seus produtos ficarão às expensas do fabricante.$$ ,4,'alterado','%148-COLOG%','Redação dada pela Portaria nº 148-COLOG/2019.'),
  ('%08-D Log%','Normas, art. 4º, § 2º — redação 2019','4º','§ 2º',null,null,null,$$Cabe ao OAC definir a forma como será realizado o ressarcimento dos custos, por ele eventualmente suportados, relativos à atividade de certificação.$$ ,4,'alterado','%148-COLOG%','Redação dada pela Portaria nº 148-COLOG/2019.'),
  ('%08-D Log%','Normas, art. 5º — redação 2019','5º',null,null,null,null,$$A avaliação da conformidade dar-se-á sob os requisitos e métodos de ensaios preconizados na legislação de referência.$$ ,4,'alterado','%148-COLOG%','Redação dada pela Portaria nº 148-COLOG/2019.'),
  ('%08-D Log%','Normas, art. 6º, caput — redação 2019','6º','caput',null,null,null,$$A solicitação para a avaliação da conformidade deve ser encaminhada pelo interessado ao OAC designado pelo Comando do Exército, instruída com os seguintes documentos capeados.$$ ,5,'alterado','%148-COLOG%','Redação dada pela Portaria nº 148-COLOG/2019.'),
  ('%08-D Log%','Normas, art. 12, caput','12',null,null,null,null,$$A importação de fogos de artifício, artigos pirotécnicos e artefatos similares está sujeita ao licenciamento não automático do Sistema de Comércio Exterior (SISCOMEX) e à autorização prévia a cargo do Comando do Exército.$$ ,7,'vigencia_a_confirmar',null,'O fluxo de comércio exterior descrito no ato é anterior à Portaria C Ex nº 2.566/2025; deve ser compatibilizado com o procedimento vigente antes de fundamentar resposta operacional.'),
  ('%08-D Log%','Normas, art. 18, caput','18',null,null,null,null,$$Para realizar qualquer operação de transporte e armazenagem, os produtos devem atender às normas estabelecidas no Decreto nº 1.797/96 e no REG/T 01.$$ ,9,'vigencia_a_confirmar',null,'O dispositivo remete a referências antigas; confirmar compatibilidade material com o marco normativo atual antes de uso como fundamento.'),
  ('%08-D Log%','Normas, art. 19','19',null,null,null,null,$$As embalagens dos produtos de que tratam estas normas devem atender às prescrições estabelecidas no Decreto nº 1.797, de 1996, no R-105, no REG/T 01 e no REG/T 02.$$ ,9,'vigencia_a_confirmar',null,'O dispositivo remete ao R-105 revogado; não usar automaticamente como fundamento material sem análise de compatibilidade.'),
  ('%08-D Log%','Normas, art. 20','20',null,null,null,null,$$As embalagens devem conter, ainda, o nome do importador, conforme registrado no Exército, sendo que todas as informações devem estar grafadas em português.$$ ,9,'vigencia_a_confirmar',null,'Manter como texto histórico/operacional até confirmação de compatibilidade com normas posteriores.'),
  ('%08-D Log%','Normas, art. 21','21',null,null,null,null,$$Os fogos de artifício destinados ao uso em ambiente fechado deverão ser identificados em sua embalagem, com a seguinte descrição: “para uso em ambiente fechado”.$$ ,9,'vigencia_a_confirmar',null,'Manter como texto histórico/operacional até confirmação de compatibilidade com normas posteriores.'),

  ('%147 COLOG%','Art. 28','28',null,null,null,null,$$O transporte de explosivos em território nacional deve ser obrigatoriamente acompanhado por escolta armada.$$ ,4,'vigente',null,null),
  ('%147 COLOG%','Art. 30 e parágrafo único','30',null,null,null,null,$$Os depósitos de explosivos deverão ter permanente monitoramento eletrônico. Parágrafo único. A gravação do monitoramento dos depósitos deve ser armazenada pelo período mínimo de trinta dias.$$ ,5,'vigente',null,null),
  ('%147 COLOG%','Art. 31, caput','31','caput',null,null,null,$$As distâncias mínimas a serem observadas com relação a edifícios habitados, ferrovias, rodovias e a outros depósitos, para fixação das quantidades de explosivos e acessórios que poderão ser armazenadas num depósito, constam das Tabelas de Quantidades-Distâncias (anexo H).$$ ,5,'vigente',null,null),
  ('%147 COLOG%','Art. 67','67',null,null,null,null,$$Os explosivos em circulação (tráfego) em todo o território nacional deverão ser acompanhados da guia de tráfego correspondente aos produtos durante todos os percursos.$$ ,12,'vigente',null,null),
  ('%147 COLOG%','Art. 69 e parágrafo único','69',null,null,null,null,$$Devem ser anexados à guia de tráfego o Termo de Transferência de Posse correspondente e o documento auxiliar da nota fiscal eletrônica (DANFE) ou documento fiscal referente aos materiais ou produtos. Parágrafo único. O Termo de Transferência de Posse deve ser assinado pelo fornecedor e pelo adquirente dos explosivos.$$ ,12,'vigente',null,null),
  ('%147 COLOG%','Art. 70','70',null,null,null,null,$$O retorno de explosivos à origem por motivo de sobra de serviço realizado, de não execução de detonação ou de devolução, poderá ser feito mediante a emissão de outra guia de tráfego ou pela utilização do verso da guia original, conforme o anexo O.$$ ,12,'vigente',null,null),
  ('%147 COLOG%','Art. 79, caput','79','caput',null,null,null,$$As pessoas autorizadas a exercerem atividades com explosivos devem comunicar ao SFPC de vinculação, via SICOEX, as ocorrências de furto, roubo, perda, extravio, desvio ou recuperação de explosivos de sua propriedade ou posse em até vinte e quatro horas após a ciência do fato.$$ ,13,'vigente',null,null),

  ('%213 COLOG%','Art. 4º, caput e incisos I a VI','4º','caput',null,null,null,$$As armas de fogo, fabricadas no país ou importadas, deverão apresentar as seguintes marcações: I – nome ou marca do fabricante; II – nome ou sigla do País; III – calibre; IV - número de série impresso na armação ou peça equivalente, no cano e no ferrolho ou culatra, quando móvel; V – o ano de fabricação quando não estiver incluído no sistema de numeração serial; e VI – o modelo da arma de fogo.$$ ,5,'vigente',null,null),
  ('%213 COLOG%','Art. 10, § 2º','10','§ 2º',null,null,null,$$O armamento somente poderá ser comercializado pela empresa importadora após realizadas as marcações previstas nestas normas e mediante a autorização do órgão de vinculação do Sistema de Fiscalização de Produtos Controlados (SisFPC).$$ ,6,'vigente',null,null),
  ('%213 COLOG%','Art. 10, § 3º','10','§ 3º',null,null,null,$$Em caso de descumprimento das marcações mínimas do §1º, a liberação alfandegária somente será procedida para reexportação ao país de origem.$$ ,6,'vigente',null,null),
  ('%213 COLOG%','Art. 11, caput','11','caput',null,null,null,$$As armas de fogo importadas diretamente por pessoa física, entidades de tiro desportivo ou caça deverão possuir somente as marcações estabelecidas no art. 4º, realizadas pelo fabricante.$$ ,6,'vigente',null,null),
  ('%213 COLOG%','Art. 12, caput','12','caput',null,null,null,$$As armas de fogo importadas, em regime temporário, devem apresentar marcações mínimas que permitam identificar e individualizar o armamento.$$ ,7,'vigente',null,null),
  ('%213 COLOG%','Art. 13, caput','13','caput',null,null,null,$$Os canos, armações e ferrolhos ou culatras móveis, produzidos como peças de reposição ou sobressalentes, nacionais ou importadas, deverão receber a mesma numeração das armas a que se destinam, precedidas da letra “R” quando reposição ou “S” quando sobressalente, de modo a identificar tais condições.$$ ,7,'vigente',null,null),

  ('%289%','Normas, art. 53, caput','53','caput',null,null,null,$$Fica permitida a aquisição de coletes balísticos até o nível IIIA (NIJ 0101.06) ou HG2 (NIJ 0101.07 e NIJ 0123.00) por pessoa física em geral.$$ ,22,'vigente',null,null),
  ('%289%','Normas, art. 54, § 2º','54','§ 2º',null,null,null,$$A responsabilidade e o ônus financeiro pelo recolhimento de EPBI expirados, irrecuperáveis ou inservíveis cabem aos órgãos, instituições e corporações elencados no art. 34, parágrafo único, do Decreto nº 9.847/2019 e no art. 75 do RPC, ressalvada a existência de procedimento próprio formalmente instituído pela respectiva entidade.$$ ,23,'vigente',null,null),
  ('%289%','Normas, art. 54, § 3º','54','§ 3º',null,null,null,$$As empresas de segurança privada deverão providenciar, junto a empresas com registro no Exército para destruição de proteção balística, a destruição dos EPBI de sua propriedade considerados expirados, irrecuperáveis ou inservíveis.$$ ,23,'vigente',null,null),
  ('%289%','Normas, art. 54, § 4º','54','§ 4º',null,null,null,$$Demais proprietários, inclusive pessoas físicas pertencentes aos órgãos, instituições e corporações mencionados, deverão buscar a destruição dos EPBI considerados expirados, irrecuperáveis ou inservíveis junto a empresas com registro no Exército para esta atividade.$$ ,23,'vigente',null,null),
  ('%289%','Normas, art. 55 e parágrafo único','55',null,null,null,null,$$A gestão do fluxo de retorno dos EPBI expirados, irrecuperáveis ou inservíveis deverá observar o programa de logística reversa implementado pelo fabricante, se houver, conforme dispõe a Lei nº 12.305, de 2 de agosto de 2010, e sua regulamentação complementar. Parágrafo único. A logística reversa deverá garantir a devolução preferencial aos fabricantes ou a empresas com registro no Exército para destruição, a rastreabilidade de todo o processo e a vedação de reincorporação dos materiais balísticos em processos de fabricação de produtos balísticos de PCE.$$ ,23,'vigente',null,null),
  ('%289%','Normas, art. 57','57',null,null,null,null,$$A pessoa jurídica autorizada a destruir blindagens balísticas, e contratada para este fim, deverá estabelecer registros próprios que identifiquem cada produto destruído, incluindo IIS, fabricante e data de destruição, mantendo-os à disposição do SisFPC pelo prazo de 5 (cinco) anos.$$ ,24,'vigente',null,null),
  ('%289%','Normas, art. 58 e parágrafo único','58',null,null,null,null,$$A destruição de EPBI consiste na inutilização física irreversível dos seus componentes, mediante desmontagem e redução física, de modo a eliminar permanentemente sua capacidade de proteção balística e impedir a reutilização, o reaproveitamento ou a reincorporação dos componentes, no todo ou em parte, como elementos balísticos em quaisquer produtos. Parágrafo único. A inutilização deverá resultar, necessariamente, na perda definitiva do valor balístico dos componentes do EPBI.$$ ,24,'vigente',null,null),

  ('%290%','Normas, art. 6º, caput e incisos I a III','6º','caput',null,null,null,$$Os seguintes serviços somente poderão ser realizados mediante Autorização Prévia do Exército, solicitada por meio do SICOVAB: I - blindagem de veículo automotor; II - aplicação de blindagem balística em viatura de OSOP; e III - fabricação de carro-forte.$$ ,6,'vigente',null,null),
  ('%290%','Normas, art. 24','24',null,null,null,null,$$Observadas a Portaria C Ex nº 2.566, de 8 de outubro de 2025, e suas revisões posteriores, bem como as normas da RFB, o controle técnico-administrativo da importação de blindagens balísticas de VAB dar-se-á também por meio do SICOVAB.$$ ,12,'vigente',null,null),
  ('%290%','Normas, art. 34','34',null,null,null,null,$$Os dados das blindagens balísticas comercializadas, fabricadas no País ou importadas, devem constar na Nota Fiscal Eletrônica (NF-e) conforme as diretivas dos Anexos G, G1 e G2.$$ ,15,'vigente',null,null),
  ('%290%','Normas, art. 39 e parágrafo único','39',null,null,null,null,$$O controle técnico-administrativo do serviço de aplicação de blindagem balística será conduzido pela RM de vinculação da blindadora e dar-se-á por meio do SICOVAB. Parágrafo único. A blindadora somente deverá instalar blindagens balísticas que atendam integralmente às especificações constantes em seu respectivo ReTEx ou Certificado de Conformidade.$$ ,16,'vigente',null,null),
  ('%290%','Normas, art. 40 e §§','40',null,null,null,null,$$O processo de aplicação de blindagem balística em embarcação, aeronave, estrutura arquitetônica e viatura de OSOP deve ser concluído em até 120 (cento e vinte) dias, a contar da data de sua abertura. O processo em viatura de OSOP só pode ser iniciado após a Autorização Prévia da RM; somente após a conclusão fica autorizada a entrega da viatura ao OSOP proprietário.$$ ,16,'vigente',null,null)
), resolved as (
  select s.*, n.id as norma_id,
         case when s.alteradora_like is null then null else (select id from public.normas na where na.titulo ilike s.alteradora_like limit 1) end as norma_alteradora_id
  from src s
  join lateral (select id from public.normas n where n.titulo ilike s.norm_like order by n.ano desc limit 1) n on true
)
insert into public.dispositivos (norma_id, referencia, artigo, paragrafo, inciso, alinea, item, texto_literal, pagina, status, norma_alteradora_id, observacao_vigencia, fonte_tipo, conferido, metadata)
select norma_id, referencia, artigo, paragrafo, inciso, alinea, item, texto_literal, pagina, status, norma_alteradora_id, observacao, 'pdf_oficial', true,
       jsonb_build_object('origem','PDF fornecido pelo usuário','carga','2026-10-07','tipo','texto_literal_conferido')
from resolved
on conflict (norma_id, referencia) do update set
  artigo=excluded.artigo,
  paragrafo=excluded.paragrafo,
  inciso=excluded.inciso,
  alinea=excluded.alinea,
  item=excluded.item,
  texto_literal=excluded.texto_literal,
  pagina=excluded.pagina,
  status=excluded.status,
  norma_alteradora_id=excluded.norma_alteradora_id,
  observacao_vigencia=excluded.observacao_vigencia,
  conferido=true,
  metadata=public.dispositivos.metadata || excluded.metadata,
  updated_at=now();
