-- Consolida a rodada de 07/10/2026 que elevou a 100% a cobertura literal dos fundamentos
-- dos Decretos 10.030/2019 e 11.615/2023, ITA 31/2025 e Portarias 1.518/2021,
-- 166/2023, 167/2024 e 213/2021.
-- A carga é idempotente por norma + referencia.

with src as (
  select n.id norma_id, d.id documento_id, n.titulo
  from normas n left join documentos d on d.norma_id=n.id
  where n.titulo in (
    'Decreto nº 10.030, de 30 de setembro de 2019',
    'Decreto nº 11.615, de 21 de julho de 2023',
    'Portaria C Ex nº 1.518, de 22 de abril de 2021',
    'Portaria nº 213 COLOG/C Ex, de 15 de setembro de 2021',
    'ITA nº 31, de 4 de setembro de 2025',
    'Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023',
    'Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024'
  )
), novos(titulo,referencia,artigo,texto_literal,pagina,status,observacao) as (values
('Decreto nº 10.030, de 30 de setembro de 2019','Anexo I, art. 24','Art. 24','As pessoas que comercializarem PCE manterão à disposição da fiscalização, período de cinco anos e na forma estabelecidos pelo Comando do Exército: I - os dados referentes aos estoques; e II - a relação das vendas efetuadas. Parágrafo único. As pessoas que comercializarem PCE manterão atualizado o sistema informatizado online para registro dos dados referentes aos estoques e às vendas de produtos controlados.',10,'vigente',null),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 38, caput e incisos I a V','Art. 38','Na concessão de CR às entidades de tiro desportivo e na fiscalização de suas atividades, o órgão fiscalizador observará os seguintes requisitos: I - distância do interessado superior a um quilômetro em relação a estabelecimentos de ensino, públicos ou privados; II - cumprimento das condições de uso e de armazenagem das armas de fogo utilizadas no estabelecimento; III - horário de funcionamento entre as seis horas e as vinte e duas horas; IV - isolamento acústico, quando aplicável; e V - apresentação de plano de segurança que contenha, no mínimo, os requisitos previstos no dispositivo.',25,'alterado','Redação consolidada com as alterações do Decreto nº 12.345/2024.'),
('Decreto nº 11.615, de 21 de julho de 2023','Art. 38-A e parágrafo único','Art. 38-A','O atirador desportivo de alto rendimento observará o disposto nesta Subseção. Parágrafo único. Também será considerado atirador desportivo de alto rendimento o atleta convocado para compor delegação oficial destinada a representar o País nos Jogos Olímpicos, nos Jogos Paralímpicos ou em campeonato mundial organizado pela ISSF ou IPSC, que deverá cumprir os demais critérios e requisitos previstos neste Decreto no período de um ano para manutenção dessa condição.',28,'vigente','Incluído pelo Decreto nº 12.345/2024.'),
('Decreto nº 11.615, de 21 de julho de 2023','Arts. 38-B a 38-E','Arts. 38-B a 38-E','Art. 38-B. Para o atirador desportivo de alto rendimento, a habitualidade de que trata o art. 35 será aferida por arma representativa de cada tipo de uso, restrito ou permitido, registrada em nome do titular. Art. 38-C. O atirador desportivo de alto rendimento poderá adquirir até dezesseis armas, das quais oito de uso restrito, desde que comprovadamente necessárias para uso na modalidade de competição em que estiver inscrito. Art. 38-D. Poderá adquirir, no período de doze meses, quantitativo de munições e insumos até 20% superior ao previsto no art. 37, caput, inciso III. Art. 38-E. Poderá obter guia de tráfego com os trajetos necessários à participação em todas as etapas do calendário nacional de competições; a guia não autoriza porte, apenas transporte desmuniciado e acondicionado no percurso necessário.',28,'vigente','Incluídos pelo Decreto nº 12.345/2024.'),
('Decreto nº 11.615, de 21 de julho de 2023','Arts. 38-F a 38-H','Arts. 38-F a 38-H','Art. 38-F. A classificação mínima será estabelecida em ato conjunto do Ministro do Esporte e do Ministro da Justiça e Segurança Pública e aferida anualmente por ranking. Art. 38-G. A Confederação ou Liga Nacional encaminhará periodicamente calendário nacional de competições e ranking nacional de atletas. Art. 38-H. O atirador de alto rendimento que não atingir a classificação mínima deixará de ter direito às prerrogativas dos arts. 38-B a 38-E.',28,'vigente','Incluídos pelo Decreto nº 12.345/2024.'),
('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 6º e parágrafo único','Art. 6º','Os PCE apreendidos, cujos destinos não tenham sido os previstos no art. 29 do Decreto-Lei nº 1.455/1976, devem ser encaminhados ao Comando do Exército por intermédio da Região Militar de vinculação da unidade administrativa que realizou a apreensão, após a solução do processo administrativo de perdimento. Parágrafo único. As RM deverão providenciar a destinação do material e verificar a pertinência da instauração de processo administrativo sancionador.',1,'vigente',null),
('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 7º','Art. 7º','Fica determinado ao Comando Logístico, por intermédio da Diretoria de Fiscalização de Produtos Controlados, a edição de Instrução Normativa regulamentando os procedimentos relativos ao recebimento, pela RM, de PCE apreendidos.',2,'vigente',null),
('Portaria C Ex nº 1.518, de 22 de abril de 2021','Art. 8º','Art. 8º','Esta Portaria entra em vigor em 1º de junho de 2021.',2,'vigente',null),
('Portaria nº 213 COLOG/C Ex, de 15 de setembro de 2021','Portaria, art. 1º','Art. 1º','Ficam aprovadas as Normas Reguladoras dos dispositivos de segurança e os procedimentos para identificação e marcação de armas de fogo e suas peças, fabricadas no país, exportadas e importadas no âmbito do SisFPC (EB 40-N-50.102), 1ª Edição, 2021.',1,'vigente',null),
('Portaria nº 213 COLOG/C Ex, de 15 de setembro de 2021','Portaria, arts. 2º e 3º','Arts. 2º e 3º','Art. 2º. Fica vigente a Portaria nº 07-DLOG, de 28 de abril de 2004 até a vigência do presente ato normativo. Art. 3º. Esta Portaria entra em vigor em 180 dias a contar da data da publicação.',1,'vigente',null),
('ITA nº 31, de 4 de setembro de 2025','Arts. 1º e 2º — autorização e apostilamento','Arts. 1º e 2º','Art. 1º A aquisição de equipamentos de recarga deve ser precedida de autorização, mediante solicitação por meio do SisGCorp. §1º A autorização poderá ser concedida para atirador desportivo e entidades de tiro. §2º O requerimento deverá ser instruído com a taxa de aquisição de PCE. Art. 2º O equipamento de recarga deve ser apostilado ao registro do adquirente, via requerimento por meio do SisGCorp. Parágrafo único. O requerimento deverá ser instruído com nota fiscal e comprovante do pagamento da taxa de apostilamento.',1,'vigente',null),
('ITA nº 31, de 4 de setembro de 2025','Arts. 3º a 6º — uso, calibres, quantidade e registro','Arts. 3º a 6º','Art. 3º Atiradores desportivos e entidades de tiro poderão adquirir equipamentos para recarga apenas para uso exclusivo nas atividades autorizadas; os calibres das matrizes devem corresponder aos calibres apostilados e somente equipamentos não pneumáticos são admitidos para recarga artesanal. Art. 4º É admitido um equipamento por calibre apostilado. Art. 5º Quem não possuir arma apostilada não poderá adquirir equipamento; equipamentos anteriores podem ser mantidos e apostilados mediante comprovação de origem. Art. 6º Os equipamentos de recarga deverão ser registrados em sistema próprio.',1,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 92 e parágrafo único','Art. 92','O CRAF das armas dos acervos de coleção, tiro desportivo e caça excepcional terá validade de três anos. Parágrafo único. Para CRAF anteriormente concedido, incidirá o prazo de validade do caput contado da data de publicação do Decreto nº 11.615/2023.',25,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 93 e §§ 1º e 2º','Art. 93','O titular do CRAF iniciará o procedimento de renovação antes da expiração do prazo. Para revalidação, cumprirá os requisitos indicados no Decreto nº 11.615/2023; as pessoas previstas no §4º do art. 6º da Lei nº 10.826/2003 apresentam apenas identificação pessoal.',25,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 94','Art. 94','A solicitação para revalidação do CRAF será realizada por meio do SisGCorp.',25,'vigente',null),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 95 e parágrafo único','Art. 95','Os atiradores são classificados em níveis conforme treinamentos e competições previstos no dispositivo. Parágrafo único. A progressão depende da permanência por doze meses em cada nível.',25,'alterado','A sistemática recebeu alterações posteriores pela Portaria nº 260/2025; consultar redação consolidada.'),
('Portaria nº 166 COLOG/C Ex, de 22 de dezembro de 2023','Normas, art. 96','Art. 96','As informações para comprovação em treinamentos e competições de tiro devem ser fornecidas pelas respectivas entidades de tiro, por meio do Anexo E.',25,'alterado','Verificar compatibilidade com alterações posteriores da Portaria nº 260/2025.'),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Portaria, art. 1º','Art. 1º','Ficam aprovadas as Normas para Aquisição, Registro, Cadastro e Transferência de Armas de fogo e a Aquisição de Munições, Insumos, Acessórios e outros produtos controlados de competência do Comando do Exército.',1,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Portaria, art. 2º','Art. 2º','Fica determinado que a Diretoria de Fiscalização de Produtos Controlados adotará, em sua área de competência, as medidas decorrentes.',1,'vigente',null),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Portaria, art. 4º — vigência consolidada','Art. 4º','Esta Portaria entra em vigor em 21 de maio de 2024.',1,'alterado','Redação consolidada após revogação da suspensão pela Portaria nº 224/2024.'),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 11 — limite anual de munição','Art. 11','A quantidade anual de munição que cada policial militar, bombeiro militar e integrante do GSI/PR poderá adquirir será de até seiscentos cartuchos por arma registrada.',8,'alterado','O parágrafo único original foi revogado pela Portaria nº 224/2024.'),
('Portaria nº 167 COLOG/C Ex, de 22 de janeiro de 2024','Normas, art. 12 e parágrafo único','Art. 12','A aquisição de munição, na indústria ou no comércio, fica condicionada à apresentação do CRAF válido da arma registrada e da identificação funcional do adquirente ao fornecedor. Parágrafo único. O fornecedor deve lançar no SICOVEM os dados do produto e do adquirente imediatamente após a venda.',8,'vigente',null)
)
insert into dispositivos (norma_id,documento_id,referencia,artigo,texto_literal,pagina,status,observacao_vigencia,fonte_tipo,conferido,metadata)
select s.norma_id,s.documento_id,n.referencia,n.artigo,n.texto_literal,n.pagina,n.status,n.observacao,'pdf_oficial',true,jsonb_build_object('origem','PDF fornecido no projeto','carga','2026-10-07_complete_core_literal')
from novos n join src s on s.titulo=n.titulo
where not exists (select 1 from dispositivos d where d.norma_id=s.norma_id and d.referencia=n.referencia);
