-- Carga inicial de dispositivos literais conferidos em fontes oficiais/consolidadas.
-- A seleção da norma/documento é por metadados; nenhum UUID gerado é fixado no script.

with n as (select id from public.normas where titulo='Decreto nº 11.615, de 21 de julho de 2023' limit 1),
     d as (select id from public.documentos where norma_id=(select id from n) order by created_at limit 1)
insert into public.dispositivos (norma_id,documento_id,referencia,artigo,texto_literal,pagina,status,fonte_tipo,conferido,metadata)
select n.id,d.id,v.referencia,v.artigo,v.texto,v.pagina,'vigente','texto_consolidado',true,jsonb_build_object('fonte','Decreto 11.615 consolidado com Decreto 12.345/2024')
from n cross join d cross join (values
('Art. 35, caput e incisos I a III','35','Art. 35. Para a concessão de CR de pessoa física a atirador desportivo pelo órgão fiscalizador, o interessado deverá estar filiado a entidade de tiro desportivo e comprometer-se a comprovar, no mínimo, por arma representativa de cada um dos tipos de arma de que tratam o art. 11, caput, incisos I, II e III, e o art. 12, caput, incisos III, IV e V: I - oito treinamentos ou competições em clube de tiro, em eventos distintos, a cada doze meses, para o atirador de nível 1; II - doze treinamentos em clube de tiro e quatro competições, das quais duas de âmbito estadual, distrital, regional ou nacional, a cada doze meses, para o atirador de nível 2; e III - vinte treinamentos em clube de tiro e seis competições, das quais duas de âmbito nacional ou internacional, no período de doze meses, para o atirador de nível 3.',24),
('Art. 35, parágrafo único','35','Parágrafo único. Além dos requisitos previstos no caput, a progressão de nível dependerá da permanência do atirador desportivo pelo prazo de doze meses em cada nível.',24),
('Art. 36, incisos I a III','36','Art. 36. Para fins de aquisição de armas de fogo, ficam estabelecidos os seguintes limites: I - atirador de nível 1 - até quatro armas de fogo de uso permitido; II - atirador de nível 2 - até oito armas de fogo de uso permitido; e III - atirador de nível 3 - até dezesseis armas de fogo, das quais até quatro poderão ser de uso restrito e as demais serão de uso permitido.',24),
('Art. 37, incisos I a III','37','Art. 37. O atirador desportivo poderá adquirir, no período de doze meses, as seguintes quantidades de munições e insumos para uso exclusivo no tiro desportivo: I - atirador de nível 1: a) até quatro mil cartuchos por atirador; e b) até oito mil cartuchos por arma .22 (ponto vinte e dois) LR ou SHORT; II - atirador de nível 2: a) até dez mil cartuchos por atirador; e b) até dezesseis mil cartuchos por arma .22 (ponto vinte e dois) LR ou SR; e III - atirador de nível 3: a) até vinte mil cartuchos por atirador; e b) até trinta e dois mil cartuchos por arma .22 (ponto vinte e dois) LR ou SR.',24),
('Art. 37, §§ 1º a 5º','37','§ 1º As munições corresponderão às armas apostiladas no CR do atirador desportivo. § 2º No requerimento utilizado pelo atirador desportivo para informar que utiliza a arma da entidade de tiro ou de outro atirador desportivo, será registrado o número de cadastro da arma de fogo e anexada a declaração de seu proprietário. § 3º O Comando do Exército poderá autorizar, em caráter excepcional, a aquisição de até quatro armas de fogo de uso restrito e de até seis mil unidades dos respectivos cartuchos por ano, para atiradores de nível 3, nos limites estritamente necessários ao desporto. § 4º A autorização excepcional prevista no § 3º não se aplica às armas de que trata o inciso I do caput do art. 12. § 5º Para os atiradores de nível 3, mediante comprovação de necessidade associada ao treinamento ou à participação em competições, o Comando do Exército poderá autorizar, motivadamente, a aquisição de armas de uso permitido e de suas munições em quantidade superior aos limites estabelecidos no art. 36 e neste artigo.',25)
) as v(referencia,artigo,texto,pagina)
on conflict (norma_id,referencia) do update set texto_literal=excluded.texto_literal,pagina=excluded.pagina,status=excluded.status,fonte_tipo=excluded.fonte_tipo,conferido=excluded.conferido,metadata=excluded.metadata,updated_at=now();

with n as (select id from public.normas where titulo='Portaria nº 147 COLOG, de 21 de novembro de 2019' limit 1),
     d as (select id from public.documentos where norma_id=(select id from n) order by created_at limit 1)
insert into public.dispositivos (norma_id,documento_id,referencia,artigo,texto_literal,pagina,status,fonte_tipo,conferido)
select n.id,d.id,v.referencia,v.artigo,v.texto,v.pagina,'vigente','pdf_oficial',true
from n cross join d cross join (values
('Art. 4º','4','Art. 4º Fica instituído o Sistema de Controle de Explosivos (SICOEX), no âmbito do Sistema de Fiscalização de Produtos Controlados (SisFPC), com a finalidade de: I – realizar o controle de explosivos; II – obter informações sobre explosivos; III – expedir autorizações de aquisição de explosivos e de prestação de serviço de detonação; e IV – emitir relatórios gerenciais e estratégicos sobre explosivos.',2),
('Art. 5º e §§ 1º e 2º','5','Art. 5º As empresas que fabricam, importam, exportam, comercializam, utilizam e prestam serviços envolvendo explosivos devem documentar os demonstrativos de entrada (anexo B) e de saída (anexo C) de explosivos por meio do SICOEX. §1º Os demonstrativos de entrada devem apresentar a origem e as especificações do produto; a identificação individual seriada (IIS) e os dados do fornecedor. §2º Os demonstrativos de saída devem apresentar o destino e especificações do produto; a identificação individual seriada (IIS) e os dados do destino.',2),
('Art. 62 e §§ 1º e 2º','62','Art. 62. A aquisição de explosivos por pessoas registradas no Exército que exerçam atividades com explosivos será autorizada por meio de requerimento ao SICOEX. §1º Devem constar do requerimento os dados do adquirente, dos produtos a serem adquiridos e do fornecedor. §2º Deve ser anexado ao requerimento o comprovante de pagamento da taxa de fiscalização correspondente.',11),
('Art. 63 e §§ 1º a 4º','63','Art. 63. A autorização para aquisição de explosivos está condicionada à existência de local de armazenagem, próprio ou terceirizado, registrado no Exército, ressalvado quando tratar-se de aquisição para emprego imediato. §1º Quando o local de armazenagem for próprio, o adquirente de explosivos deverá ter apostilada ao seu registro a atividade PRESTAÇÃO DE SERVIÇO (PRÓPRIO) – ARMAZENAGEM DE EXPLOSIVOS. §2º Quando o local de armazenagem for terceirizado, o adquirente de explosivos deverá apresentar um contrato de locação com empresa que possua apostilada ao seu registro a atividade PRESTAÇÃO DE SERVIÇO – ARMAZENAGEM DE EXPLOSIVOS. §3º No caso de aquisição de explosivos para emprego imediato, a entrega deve ser realizada na data prevista para a execução do serviço de detonação. §4º Enquanto não for disponibilizada a aquisição de explosivos por meio do SICOEX, deve ser utilizado o anexo M, que poderá ser encaminhado por meio eletrônico disponibilizado pelo Serviço de Fiscalização de Produtos Controlados.',11),
('Art. 64 e §§ 1º e 2º','64','Art. 64. As pessoas isentas de registro no Exército, conforme o art. 7º do Decreto nº 10.030, de 2019, deverão solicitar autorização para aquisição de explosivos à Organização Militar do SisFPC, utilizando o requerimento previsto no anexo M. §1º Deve constar do requerimento as informações sobre o requerente e os produtos a serem adquiridos e a exposição de motivos para a aquisição dos explosivos. §2º Deve ser anexado ao requerimento o comprovante de pagamento da taxa correspondente.',11),
('Art. 65','65','Art. 65. A autorização para aquisição de explosivos de que trata o art. 64 terá a validade de até noventa dias, a contar da sua expedição, e deve ser exarada no próprio requerimento.',11),
('Arts. 66 a 69','66-69','Art. 66. É vedada a transferência de posse de explosivo para pessoa que não estejam autorizadas a adquirir explosivos. Art. 67. Os explosivos em circulação (tráfego) em todo o território nacional deverão ser acompanhados da guia de tráfego correspondente aos produtos durante todos os percursos. Art. 68. Explosivos e acessórios iniciadores transportados nas condições previstas no art. 25 podem constar da mesma guia de tráfego (GT). Art. 69. Devem ser anexados à guia de tráfego o Termo de Transferência de Posse (anexo N) correspondente; e o documento auxiliar da nota fiscal eletrônica (DANFE) ou documento fiscal referente aos materiais ou produtos. Parágrafo único. O Termo de Transferência de Posse deve ser assinado pelo fornecedor e pelo adquirente dos explosivos.',12)
) as v(referencia,artigo,texto,pagina)
on conflict (norma_id,referencia) do update set texto_literal=excluded.texto_literal,pagina=excluded.pagina,status=excluded.status,fonte_tipo=excluded.fonte_tipo,conferido=excluded.conferido,updated_at=now();

with n as (select id from public.normas where titulo='Portaria nº 213 COLOG/C Ex, de 15 de setembro de 2021' limit 1),
     d as (select id from public.documentos where norma_id=(select id from n) order by created_at limit 1)
insert into public.dispositivos (norma_id,documento_id,referencia,artigo,texto_literal,pagina,status,fonte_tipo,conferido)
select n.id,d.id,v.referencia,v.artigo,v.texto,v.pagina,'vigente','pdf_oficial',true
from n cross join d cross join (values
('Art. 3º','3','Art. 3º A marcação e identificação de armas de fogo tem por finalidade realizar o rastreamento, de acordo com o art. 86 e 87 do Decreto nº 10.030, de 2019.',4),
('Art. 10, caput e § 1º','10','Art. 10 As armas de fogo importadas deverão estar marcadas de maneira que permitam a identificação da empresa importadora, conforme previsto na alínea “b”, do nº 1, do art. 6º, do Decreto Legislativo nº 3.229, de 29 de outubro de 1999, além das marcações estabelecidas no art. 4º, destas normas. §1º Admite-se a execução de marcações no Brasil, desde que solicitado previamente pela empresa importadora ao Comando Logístico e que o serviço seja realizado por pessoa física ou jurídica especializada, devendo a arma possuir ao menos as marcações mínimas previstas na norma.',6),
('Art. 14 e §§','14','Art. 14 O Comando Logístico, por intermédio da DFPC, poderá autorizar a remarcação de armas de fogo cuja identificação e marcações tenham sido suprimidas ou adulteradas. §1º A solicitação de remarcação deverá ser acompanhada de laudo pericial emitido por órgão de criminalística, laboratório técnico particular ou instituição de estudos e pesquisas criminais que possam recuperar integralmente os dados da marcação original.',8)
) as v(referencia,artigo,texto,pagina)
on conflict (norma_id,referencia) do update set texto_literal=excluded.texto_literal,pagina=excluded.pagina,status=excluded.status,fonte_tipo=excluded.fonte_tipo,conferido=excluded.conferido,updated_at=now();
