-- Expande normas identificadas pela auditoria como cobertura baixa.
-- Conteúdo estruturado a partir dos PDFs do projeto; são sínteses fiéis, não transcrições integrais.

with novos(titulo,pagina,dispositivo,conteudo) as (
values
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',6,'Normas, art. 1º — limites de aquisição','Militares do Exército, da ativa e na inatividade, podem adquirir até seis armas de fogo, das quais até cinco podem ser de uso restrito. Quantidade superior pode ser autorizada excepcionalmente pelo COLOG mediante justificativa; quem já possuía quantidade superior tem a propriedade assegurada.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',6,'Normas, arts. 2º e 3º — impedimentos e marcação','Veda autorização de aquisição para militares em formação, no Serviço Militar Inicial, praças com comportamento mau ou insuficiente, inaptos psicologicamente ou envolvidos em determinadas situações criminais. As armas pessoais tratadas pela norma não devem ser brasonadas nem marcadas com nome ou distintivo institucional.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',7,'Normas, art. 4º — aquisição, registro e cadastro','A aquisição no comércio ou indústria depende de autorização da OM de vinculação, observância dos limites e requerimento instruído com os documentos exigidos. A autorização de aquisição tem validade de 180 dias. Após a compra, seguem-se registro, cadastro no SIGMA e emissão do CRAF.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',9,'Normas, arts. 7º a 10 — porte de arma','Oficiais e determinadas categorias de subtenentes e sargentos possuem regras próprias de porte. A comprovação é feita pela identificação militar e CRAF; militares inativos devem observar avaliação psicológica periódica prevista na norma. Em hipóteses excepcionais, outras categorias podem obter autorização fundamentada.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',10,'Normas, arts. 11 a 19 — condições e revogação do porte','O porte tem abrangência nacional, não autoriza condução ostensiva e pode ser negado ou revogado nas hipóteses previstas, mediante decisão motivada. A norma disciplina também substituição do CRAF e possibilidade de novo pedido após cessadas as causas impeditivas.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',11,'Normas, arts. 20 a 25 — transferência de propriedade','Regula transferências de armas de uso permitido ou restrito entre pessoas autorizadas. Define procedimentos para SIGMA→SIGMA, SINARM→SIGMA e SIGMA→SINARM, com requerimento, documentos, anuência, atualização cadastral e emissão de novo CRAF conforme o caso.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',12,'Normas, arts. 26 a 28 — munição, insumos e acessórios','Permite ao militar adquirir anualmente até seiscentos cartuchos por arma registrada, ou insumos para recarga dentro do mesmo limite total. A compra de munição exige CRAF válido e identificação funcional; acessórios considerados PCE dependem de autorização.'),
('Portaria nº 164 COLOG/C Ex, de dezembro de 2023',13,'Normas, arts. 29 a 36 — transporte e disposições finais','Arma de militar sem autorização de porte deve ser transportada com Guia de Tráfego. A norma também disciplina comunicação de extravio, furto, roubo e recuperação ao SIGMA, transferência ao SINARM em caso de exclusão das Forças Armadas e outras disposições finais.'),
('Portaria C Ex nº 1.518, de 22 de abril de 2021',1,'Arts. 1º e 2º — destinação de PCE apreendido pela RFB','Estabelece procedimentos administrativos para destinação de PCE apreendidos pela Receita Federal. A destinação segue a legislação aduaneira indicada, com tratamento específico para explosivos, armas de fogo, partes, peças controladas e munições.'),
('Portaria C Ex nº 1.518, de 22 de abril de 2021',1,'Arts. 3º e 4º — químicos, pirotécnicos, proteção balística, pressão e armas','PCE dos tipos químicos, pirotécnicos, proteção balística e armas de pressão apreendidos devem ser destruídos ou inutilizados nas condições previstas. Armas de fogo apreendidas devem ser informadas à Polícia Federal para cadastro no SINARM e verificação de indícios de infração penal.'),
('Portaria C Ex nº 1.518, de 22 de abril de 2021',1,'Arts. 5º e 6º — encaminhamento e destinação','Armas de fogo que não mais interessem à persecução penal são encaminhadas ao Comando do Exército para destruição ou doação nas hipóteses legais. Outros PCE, após processo de perdimento, são encaminhados por intermédio da Região Militar competente para destinação.'),
('Portaria C Ex nº 1.518, de 22 de abril de 2021',2,'Arts. 7º e 8º — regulamentação e vigência','Determina ao COLOG, por meio da DFPC, a edição de instrução normativa para procedimentos de recebimento de PCE apreendidos pelas Regiões Militares e fixa a entrada em vigor em 1º de junho de 2021.'),
('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023',1,'Arts. 1º e 2º — parâmetros e definições','Estabelece parâmetros de aferição e listagens de calibres nominais, com suas energias, para classificação de armas de fogo e munições como de uso permitido ou restrito, além de definir conceitos técnicos usados na classificação.'),
('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023',2,'Arts. 3º a 7º — anexos de classificação','Distribui pelos Anexos A a F as listagens de calibres permitidos e restritos conforme tipo de arma e determina que calibres não listados ou não padronizados sejam submetidos ao Exército e à Polícia Federal para classificação. O Anexo G contém parâmetros de aferição e cálculo de energia.'),
('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023',2,'Arts. 8º, 8º-A e 9º — armas longas semiautomáticas e multicalibre','Na redação consolidada indicada no documento, armas longas raiadas semiautomáticas de calibre nominal igual ou inferior a .22 Long Rifle são de uso permitido e as superiores são de uso restrito. Armas multicalibre consideram a munição de maior energia e, quando aplicável, a classificação mais restritiva. Regras alteradas/incluídas pela Portaria Conjunta nº 4/2025.'),
('Portaria Conjunta C Ex/DG-PF nº 2, de 6 de novembro de 2023',2,'Arts. 10 a 12 — revogação, prazo e vigência','Revoga a Portaria C Ex nº 1.222/2019, estabelece que o prazo de 90 dias referido no art. 79, §2º, do Decreto nº 11.615/2023 conta da publicação desta Portaria Conjunta e determina vigência na data de publicação.'),
('Portaria nº 08-D Log, de 29 de outubro de 2008',3,'Normas, arts. 1º a 3º — finalidade e avaliação obrigatória','Regula fabricação, importação, avaliação, desembaraço, transporte, armazenagem e embalagens de fogos de artifício, artifícios pirotécnicos e similares. Produtos nacionais ou importados devem ser submetidos à avaliação de conformidade conforme a legislação de referência.'),
('Portaria nº 08-D Log, de 29 de outubro de 2008',4,'Normas, arts. 4º a 11 — avaliação da conformidade','Na redação alterada pela Portaria nº 148-COLOG/2019, a avaliação da conformidade é realizada por Organismo de Avaliação da Conformidade e segue requisitos e métodos de ensaio da legislação de referência. Produtos não conformes podem ser reavaliados e produtos conformes permanecem sujeitos a verificações posteriores.'),
('Portaria nº 08-D Log, de 29 de outubro de 2008',7,'Normas, arts. 12 a 17 — importação e desembaraço','A importação de fogos e artigos pirotécnicos depende de licenciamento não automático e autorização prévia do Comando do Exército. A norma disciplina documentação, finalidade da importação, restrições, integridade do produto e condições para desembaraço alfandegário.'),
('Portaria nº 08-D Log, de 29 de outubro de 2008',9,'Normas, arts. 18 a 21 — transporte, armazenagem e embalagens','Transporte e armazenagem devem observar as normas de segurança indicadas, com armazenagem em depósitos devidamente apostilados. Embalagens devem atender às prescrições aplicáveis, identificar o importador em português e, quando for o caso, indicar uso em ambiente fechado.'),
('Portaria nº 08-D Log, de 29 de outubro de 2008',10,'Normas, arts. 22 a 27 — disposições transitórias','Disciplina a regularização e reavaliação de produtos nacionais e importados já avaliados, manutenção de conformidade, validade de laudos antigos e possibilidade de nova avaliação, além de regras transitórias para comprovação de avaliação por laboratório acreditado.')
),
base as (
  select v.*,n.id norma_id,d.id documento_id
  from novos v
  join public.normas n on n.titulo=v.titulo
  left join public.documentos d on d.norma_id=n.id
)
insert into public.trechos(norma_id,documento_id,pagina,dispositivo,conteudo,metadata)
select norma_id,documento_id,pagina,dispositivo,conteudo,
       jsonb_build_object('origem','PDF enviado','tipo','sintese_fiel','expansao_auditoria','2026-10-06')
from base b
where not exists (
  select 1 from public.trechos t
  where t.norma_id=b.norma_id
    and lower(coalesce(t.dispositivo,''))=lower(coalesce(b.dispositivo,''))
);
